name: Feature request
description: Suggest an idea for this project.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
       Please fill out the following fields with as much detail as possible:
  - type: textarea
    id: feature
    attributes:
      label: Description of the feature or enhancement you'd like to see in VidCoder
    validations:
      required: true
