//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EncodingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncodingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.EncodingRes", typeof(EncodingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string AdaptiveBFrames_Fast {
            get {
                return ResourceManager.GetString("AdaptiveBFrames_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string AdaptiveBFrames_Off {
            get {
                return ResourceManager.GetString("AdaptiveBFrames_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal.
        /// </summary>
        public static string AdaptiveBFrames_Optimal {
            get {
                return ResourceManager.GetString("AdaptiveBFrames_Optimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive B-Frames:.
        /// </summary>
        public static string AdaptiveBFramesLabel {
            get {
                return ResourceManager.GetString("AdaptiveBFramesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive Direct Mode:.
        /// </summary>
        public static string AdaptiveDirectModeLabel {
            get {
                return ResourceManager.GetString("AdaptiveDirectModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive Quantization Strength:.
        /// </summary>
        public static string AdaptiveQuantizationStrengthLabel {
            get {
                return ResourceManager.GetString("AdaptiveQuantizationStrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio encoding.
        /// </summary>
        public static string AddAudioEncodingButton {
            get {
                return ResourceManager.GetString("AddAudioEncodingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x264 has a variety of algorithms to decide when to use B-frames and how many to use.
        ///
        ///Fast mode takes roughly the same amount of time no matter how many B-frames you specify.  However, while fast, its decisions are often suboptimal.
        ///
        ///Optimal mode gets slower as the maximum number of B-Frames increases, but makes much more accurate decisions, especially when used with B-pyramid..
        /// </summary>
        public static string Advanced_AdaptiveBFramesToolTip {
            get {
                return ResourceManager.GetString("Advanced_AdaptiveBFramesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.264 allows for two different prediction modes, spatial and temporal, in B-frames.
        ///
        ///Spatial, the default, is almost always better, but temporal is sometimes useful too.
        ///
        ///x264 can, at the cost of a small amount of speed (and accordingly for a small compression gain), adaptively select which is better for each particular frame..
        /// </summary>
        public static string Advanced_AdaptiveDirectModeToolTip {
            get {
                return ResourceManager.GetString("Advanced_AdaptiveDirectModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive quantization controls how the encoder distributes bits across the frame.
        ///Higher values take more bits away from edges and complex areas to improve areas with finer detail..
        /// </summary>
        public static string Advanced_AdaptiveQuantizationStrengthToolTip {
            get {
                return ResourceManager.GetString("Advanced_AdaptiveQuantizationStrengthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode decision picks from a variety of options to make its decision: this option chooses what options those are.  
        ///Fewer partitions to check means faster encoding, at the cost of worse decisions, since the best option might have been one that was turned off..
        /// </summary>
        public static string Advanced_AnalysisToolTip {
            get {
                return ResourceManager.GetString("Advanced_AnalysisToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sane values are ~2-5.  
        ///This specifies the maximum number of sequential B-frames that the encoder can use. 
        /// Large numbers generally won&apos;t help significantly unless Adaptive B-frames is set to Optimal.  
        ///Cel-animated source material and B-pyramid also significantly increase the usefulness of larger values. 
        ///Baseline profile, as required for iPods and similar devices, requires B-frames to be set to 0 (off)..
        /// </summary>
        public static string Advanced_BFramesToolTip {
            get {
                return ResourceManager.GetString("Advanced_BFramesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the encoder has done its work, it has a bunch of data that needs to be compressed losslessly, similar to ZIP or RAR. H.264 provides two options for this: CAVLC and CABAC.  CABAC decodes a lot slower but compresses significantly better (10-30%), especially at lower bitrates. If you&apos;re looking to minimize CPU requirements for video playback, disable this option. Baseline profile, as required for iPods and similar devices, requires CABAC to be disabled..
        /// </summary>
        public static string Advanced_CabacToolTip {
            get {
                return ResourceManager.GetString("Advanced_CabacToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.264 has a built-in deblocking filter that smooths out blocking artifacts after decoding each frame.  This not only improves visual quality, but also helps compression significantly. 
        ///The deblocking filter takes a lot of CPU power, so if you&apos;re looking to minimize CPU requirements for video playback, disable it.
        ///
        ///The deblocking filter has two adjustable parameters, &quot;strength&quot; and &quot;threshold&quot;. 
        ///The former controls how strong (or weak) the deblocker is, while the latter controls how many (or few)  edges  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Advanced_DeblockingToolTip {
            get {
                return ResourceManager.GetString("Advanced_DeblockingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 8x8 transform is the single most useful feature of x264 in terms of compression-per-speed.  
        ///It improves compression by at least 5% at a very small speed cost and may provide an unusually high visual quality benefit compared to its compression gain.  
        ///However, it requires High Profile, which many devices may not support..
        /// </summary>
        public static string Advanced_EightByEightDctToolTip {
            get {
                return ResourceManager.GetString("Advanced_EightByEightDctToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the motion estimation method. Motion estimation is how the encoder estimates how each block of pixels in a frame has moved.  
        ///A better motion search method improves compression at the cost of speed.
        ///
        ///Diamond: performs an extremely fast and simple search using a diamond pattern.
        ///
        ///Hexagon: performs a somewhat more effective but slightly slower search using a hexagon pattern.
        ///
        ///Uneven Multi-Hex: performs a very wide search using a variety of patterns, more accurately capturing complex motion.
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Advanced_MotionEstimationMethodToolTip {
            get {
                return ResourceManager.GetString("Advanced_MotionEstimationMethodToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the distance x264 searches from its best guess at the motion of a block in order to try to find its actual motion.  
        ///
        ///The default is fine for most content, but extremely high motion video, especially at HD resolutions, may benefit from higher ranges, albeit at a high speed cost.
        ///
        ///Valid values are 4-16 for Diamond and Hexagon methods and 4-64 for other methods..
        /// </summary>
        public static string Advanced_MotionEstimationRangeToolTip {
            get {
                return ResourceManager.GetString("Advanced_MotionEstimationRangeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x264 normally zeroes out nearly-empty data blocks to save bits to be better used for some other purpose in the video.  
        ///However, this can sometimes have slight negative effects on retention of subtle grain and dither.  
        ///Don&apos;t touch this unless you&apos;re having banding issues or other such cases where you are having trouble keeping fine noise..
        /// </summary>
        public static string Advanced_NoDctDecimateToolTip {
            get {
                return ResourceManager.GetString("Advanced_NoDctDecimateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychovisual.
        /// </summary>
        public static string Advanced_PsychovisualLabel {
            get {
                return ResourceManager.GetString("Advanced_PsychovisualLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychovisual Rate Distortion means x264 tries to retain detail, for better quality to the human eye, 
        ///as opposed to trying to maximize quality the way a computer understands it, through signal-to-noise ratios that have trouble telling apart fine detail and noise..
        /// </summary>
        public static string Advanced_PsychovisualRateDistortionToolTip {
            get {
                return ResourceManager.GetString("Advanced_PsychovisualRateDistortionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychovisual Trellis tries to retain more sharpness and detail, but can cause artifacting.
        ///It is considered experimental, which is why it&apos;s off by default. Good values are 0.1 to 0.2..
        /// </summary>
        public static string Advanced_PsychovisualTrellisToolTip {
            get {
                return ResourceManager.GetString("Advanced_PsychovisualTrellisToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-pyramid creates a pyramidal structure (hence the name) of B-frames, allowing B-frames to 
        ///reference each other to improve compression.  
        ///
        ///Requires Max B-frames greater than 1; optimal adaptive B-frames is strongly recommended for full compression benefit..
        /// </summary>
        public static string Advanced_PyramidalBFramesToolTip {
            get {
                return ResourceManager.GetString("Advanced_PyramidalBFramesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sane values are ~1-6.
        ///
        ///The more you add, the better the compression, but the slower the encode.
        ///
        ///Cel animation tends to benefit from more reference frames a lot more than film content.
        ///
        ///Note that many hardware devices have limitations on the number of supported reference frames, so if you&apos;re encoding for a handheld or standalone player, don&apos;t touch this unless you&apos;re absolutely sure you know what you&apos;re doing!.
        /// </summary>
        public static string Advanced_ReferenceFramesToolTip {
            get {
                return ResourceManager.GetString("Advanced_ReferenceFramesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting controls both subpixel-precision motion estimation and mode decision methods.
        ///
        ///Subpixel motion estimation is used for refining motion estimates beyond mere pixel accuracy, improving compression.
        ///
        ///Mode decision is the method used to choose how to encode each block of the frame: a very important decision.
        ///
        ///SAD is the fastest method, followed by SATD, RD, RD refinement, and the slowest, QPRD.
        ///6 or higher is strongly recommended: Psy-RD, a very powerful psy optimization that helps retain det [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Advanced_SubpixelMotionEstimationToolTip {
            get {
                return ResourceManager.GetString("Advanced_SubpixelMotionEstimationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trellis fine-tunes the rounding of transform coefficients to squeeze out 3-5% more compression at the cost of some speed. 
        ///&quot;Always&quot; uses trellis not only during the main encoding process, but also during analysis, which improves compression even more, albeit at great speed cost. 
        ///
        ///Trellis costs more speed at higher bitrates..
        /// </summary>
        public static string Advanced_TrellisToolTip {
            get {
                return ResourceManager.GetString("Advanced_TrellisToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs extra analysis to decide upon weighting parameters for each frame.  
        ///This improves overall compression slightly and improves the quality of fades greatly. 
        ///Baseline profile, as required for iPods and similar devices, requires weighted P-frame prediction to be disabled.  
        ///Note that some devices and players, even those that support Main Profile, 
        ///may have problems with Weighted P-frame prediction: the Apple TV is completely incompatible with it, for example..
        /// </summary>
        public static string Advanced_WeightPToolTip {
            get {
                return ResourceManager.GetString("Advanced_WeightPToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional advanced x264 options:.
        /// </summary>
        public static string AdvancedOptionsStringLabel {
            get {
                return ResourceManager.GetString("AdvancedOptionsStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Query.
        /// </summary>
        public static string AdvancedQuery {
            get {
                return ResourceManager.GetString("AdvancedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Analysis_All {
            get {
                return ResourceManager.GetString("Analysis_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most.
        /// </summary>
        public static string Analysis_Most {
            get {
                return ResourceManager.GetString("Analysis_Most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Analysis_None {
            get {
                return ResourceManager.GetString("Analysis_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some.
        /// </summary>
        public static string Analysis_Some {
            get {
                return ResourceManager.GetString("Analysis_Some", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anamorphic:.
        /// </summary>
        public static string AnamorphicLabel {
            get {
                return ResourceManager.GetString("AnamorphicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High values mean high compression: better quality/smaller size but longer encode times..
        /// </summary>
        public static string AscendingCompressionToolTip {
            get {
                return ResourceManager.GetString("AscendingCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High values mean high quality..
        /// </summary>
        public static string AscendingQualityToolTip {
            get {
                return ResourceManager.GetString("AscendingQualityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Range Compression. Valid values are 0-4.
        ///
        ///For source audio that has a wide dynamic range (very loud and very soft sequences), DRC allows you to &quot;compress&quot; the range by making loud sections softer and soft sections louder.
        ///
        ///This only works with AC3 sources..
        /// </summary>
        public static string Audio_DrcToolTip {
            get {
                return ResourceManager.GetString("Audio_DrcToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplify or attenuate audio before encoding. Valid values are -20 to +20 dB..
        /// </summary>
        public static string Audio_GainToolTip {
            get {
                return ResourceManager.GetString("Audio_GainToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of compression to apply. {0} Valid values are from {1} to {2}..
        /// </summary>
        public static string AudioCompressionToolTip {
            get {
                return ResourceManager.GetString("AudioCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC3.
        /// </summary>
        public static string AudioEncoder_ac3 {
            get {
                return ResourceManager.GetString("AudioEncoder_ac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC (avcodec).
        /// </summary>
        public static string AudioEncoder_av_aac {
            get {
                return ResourceManager.GetString("AudioEncoder_av_aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC (FAAC).
        /// </summary>
        public static string AudioEncoder_faac {
            get {
                return ResourceManager.GetString("AudioEncoder_faac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC (FDK).
        /// </summary>
        public static string AudioEncoder_fdk_aac {
            get {
                return ResourceManager.GetString("AudioEncoder_fdk_aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE-AAC (FDK).
        /// </summary>
        public static string AudioEncoder_fdk_haac {
            get {
                return ResourceManager.GetString("AudioEncoder_fdk_haac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC 16-bit.
        /// </summary>
        public static string AudioEncoder_flac16 {
            get {
                return ResourceManager.GetString("AudioEncoder_flac16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC 24-bit.
        /// </summary>
        public static string AudioEncoder_flac24 {
            get {
                return ResourceManager.GetString("AudioEncoder_flac24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        public static string AudioEncoder_mp3 {
            get {
                return ResourceManager.GetString("AudioEncoder_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough.
        /// </summary>
        public static string AudioEncoder_Passthrough {
            get {
                return ResourceManager.GetString("AudioEncoder_Passthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis.
        /// </summary>
        public static string AudioEncoder_vorbis {
            get {
                return ResourceManager.GetString("AudioEncoder_vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio quality target. {0} Valid values are from {1} to {2}..
        /// </summary>
        public static string AudioQualityToolTip {
            get {
                return ResourceManager.GetString("AudioQualityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (auto).
        /// </summary>
        public static string AutoCaption {
            get {
                return ResourceManager.GetString("AutoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback:.
        /// </summary>
        public static string AutoPassthroughFallbackLabel {
            get {
                return ResourceManager.GetString("AutoPassthroughFallbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough does not work on all audio codecs. This specifies the encoder to fall back to if the track cannot be passed through..
        /// </summary>
        public static string AutoPassthroughFallbackToolTip {
            get {
                return ResourceManager.GetString("AutoPassthroughFallbackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Bitrate (kbps).
        /// </summary>
        public static string AverageBitrateRadioButton {
            get {
                return ResourceManager.GetString("AverageBitrateRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string Bitrate {
            get {
                return ResourceManager.GetString("Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate:.
        /// </summary>
        public static string BitrateLabel {
            get {
                return ResourceManager.GetString("BitrateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CABAC:.
        /// </summary>
        public static string CabacLabel {
            get {
                return ResourceManager.GetString("CabacLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the listed framerate from the source title for a constant framerate..
        /// </summary>
        public static string CfrSameAsSourceToolTip {
            get {
                return ResourceManager.GetString("CfrSameAsSourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a constant frame rate..
        /// </summary>
        public static string CfrToolTip {
            get {
                return ResourceManager.GetString("CfrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Layout.
        /// </summary>
        public static string ChannelLayout {
            get {
                return ResourceManager.GetString("ChannelLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        public static string CodecLabel {
            get {
                return ResourceManager.GetString("CodecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Framerate.
        /// </summary>
        public static string ConstantFramerateRadioButton {
            get {
                return ResourceManager.GetString("ConstantFramerateRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Quality.
        /// </summary>
        public static string ConstantQualityRadioButton {
            get {
                return ResourceManager.GetString("ConstantQualityRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container:.
        /// </summary>
        public static string ContainerLabel {
            get {
                return ResourceManager.GetString("ContainerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropping.
        /// </summary>
        public static string CroppingLabel {
            get {
                return ResourceManager.GetString("CroppingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deblocking:.
        /// </summary>
        public static string DeblockingLabel {
            get {
                return ResourceManager.GetString("DeblockingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deblock:.
        /// </summary>
        public static string DeblockLabel {
            get {
                return ResourceManager.GetString("DeblockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomb:.
        /// </summary>
        public static string DecombLabel {
            get {
                return ResourceManager.GetString("DecombLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Default).
        /// </summary>
        public static string DefaultFormat {
            get {
                return ResourceManager.GetString("DefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterlace:.
        /// </summary>
        public static string DeinterlaceLabel {
            get {
                return ResourceManager.GetString("DeinterlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoise:.
        /// </summary>
        public static string DenoiseLabel {
            get {
                return ResourceManager.GetString("DenoiseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low values mean high compression: better quality/smaller size but longer encode times..
        /// </summary>
        public static string DescendingCompressionToolTip {
            get {
                return ResourceManager.GetString("DescendingCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low values mean high quality..
        /// </summary>
        public static string DescendingQualityToolTip {
            get {
                return ResourceManager.GetString("DescendingQualityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detelecine:.
        /// </summary>
        public static string DetelecineLabel {
            get {
                return ResourceManager.GetString("DetelecineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string DirectPrediction_Automatic {
            get {
                return ResourceManager.GetString("DirectPrediction_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DirectPrediction_None {
            get {
                return ResourceManager.GetString("DirectPrediction_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial.
        /// </summary>
        public static string DirectPrediction_Spatial {
            get {
                return ResourceManager.GetString("DirectPrediction_Spatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal.
        /// </summary>
        public static string DirectPrediction_Temporal {
            get {
                return ResourceManager.GetString("DirectPrediction_Temporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Resolution:.
        /// </summary>
        public static string DisplayResolutionLabel {
            get {
                return ResourceManager.GetString("DisplayResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Width:.
        /// </summary>
        public static string DisplayWidthRadioButton {
            get {
                return ResourceManager.GetString("DisplayWidthRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired display width of the video. Other parameters such as the Pixel Aspect Ratio will be changed to achieve this..
        /// </summary>
        public static string DisplayWidthToolTip {
            get {
                return ResourceManager.GetString("DisplayWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRC:.
        /// </summary>
        public static string DrcLabel {
            get {
                return ResourceManager.GetString("DrcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few players support playback of DTS audio in MP4 containers. MKV is recommended for DTS audio..
        /// </summary>
        public static string DtsMp4Warning {
            get {
                return ResourceManager.GetString("DtsMp4Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8x8 Transform:.
        /// </summary>
        public static string EightByEightTransformLabel {
            get {
                return ResourceManager.GetString("EightByEightTransformLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder.
        /// </summary>
        public static string Encoder {
            get {
                return ResourceManager.GetString("Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder Settings.
        /// </summary>
        public static string EncoderSettings {
            get {
                return ResourceManager.GetString("EncoderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset: {0}.
        /// </summary>
        public static string EncodingWindowTitle {
            get {
                return ResourceManager.GetString("EncodingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension:.
        /// </summary>
        public static string ExtensionLabel {
            get {
                return ResourceManager.GetString("ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.###} FPS.
        /// </summary>
        public static string FpsFormat {
            get {
                return ResourceManager.GetString("FpsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate (FPS):.
        /// </summary>
        public static string FramerateLabel {
            get {
                return ResourceManager.GetString("FramerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain (dB):.
        /// </summary>
        public static string GainLabel {
            get {
                return ResourceManager.GetString("GainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale encoding.
        /// </summary>
        public static string GrayscaleCheckBox {
            get {
                return ResourceManager.GetString("GrayscaleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.264 Level:.
        /// </summary>
        public static string H264LevelLabel {
            get {
                return ResourceManager.GetString("H264LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets and ensures compliance with the specified H.264 level.
        ///
        ///Overrides all other settings..
        /// </summary>
        public static string H264LevelToolTip {
            get {
                return ResourceManager.GetString("H264LevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.264 Profile:.
        /// </summary>
        public static string H264ProfileLabel {
            get {
                return ResourceManager.GetString("H264ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality.
        /// </summary>
        public static string HighQuality {
            get {
                return ResourceManager.GetString("HighQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include chapter markers.
        /// </summary>
        public static string IncludeChapterMarkersCheckBox {
            get {
                return ResourceManager.GetString("IncludeChapterMarkersCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include chapter markers from the input video in the encoded video..
        /// </summary>
        public static string IncludeChapterMarkersToolTip {
            get {
                return ResourceManager.GetString("IncludeChapterMarkersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod 5G support.
        /// </summary>
        public static string Ipod5GSupportCheckBox {
            get {
                return ResourceManager.GetString("Ipod5GSupportCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a marker to the file that older iPods require before they&apos;ll allow H.264 video to sync..
        /// </summary>
        public static string IPod5GSupportToolTip {
            get {
                return ResourceManager.GetString("IPod5GSupportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Aspect Ratio.
        /// </summary>
        public static string KeepAspectRatioCheckBox {
            get {
                return ResourceManager.GetString("KeepAspectRatioCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large file size.
        /// </summary>
        public static string LargeFileSizeCheckBox {
            get {
                return ResourceManager.GetString("LargeFileSizeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows files over 4GB. When enabled, uses 64-bit numbers in encoding. Some devices such as the iPod and PS3 are incompatible with this option..
        /// </summary>
        public static string LargeFileSizeToolTip {
            get {
                return ResourceManager.GetString("LargeFileSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low quality.
        /// </summary>
        public static string LowQuality {
            get {
                return ResourceManager.GetString("LowQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum B-Frames:.
        /// </summary>
        public static string MaxBFramesLabel {
            get {
                return ResourceManager.GetString("MaxBFramesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Height:.
        /// </summary>
        public static string MaxHeightLabel {
            get {
                return ResourceManager.GetString("MaxHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Width:.
        /// </summary>
        public static string MaxWidthLabel {
            get {
                return ResourceManager.GetString("MaxWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.1 (5F/2R/LFE).
        /// </summary>
        public static string Mixdown_5_2_lfe {
            get {
                return ResourceManager.GetString("Mixdown_5_2_lfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1 Channels.
        /// </summary>
        public static string Mixdown_5point1 {
            get {
                return ResourceManager.GetString("Mixdown_5point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Surround.
        /// </summary>
        public static string Mixdown_dpl1 {
            get {
                return ResourceManager.GetString("Mixdown_dpl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Pro Logic II.
        /// </summary>
        public static string Mixdown_dpl2 {
            get {
                return ResourceManager.GetString("Mixdown_dpl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono (Left Only).
        /// </summary>
        public static string Mixdown_left_only {
            get {
                return ResourceManager.GetString("Mixdown_left_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string Mixdown_mono {
            get {
                return ResourceManager.GetString("Mixdown_mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono (Right Only).
        /// </summary>
        public static string Mixdown_right_only {
            get {
                return ResourceManager.GetString("Mixdown_right_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string Mixdown_stereo {
            get {
                return ResourceManager.GetString("Mixdown_stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixdown:.
        /// </summary>
        public static string MixdownLabel {
            get {
                return ResourceManager.GetString("MixdownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus:.
        /// </summary>
        public static string ModulusLabel {
            get {
                return ResourceManager.GetString("ModulusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Settings:.
        /// </summary>
        public static string MoreSettingsLabel {
            get {
                return ResourceManager.GetString("MoreSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string MotionEstimationMethod_Diamond {
            get {
                return ResourceManager.GetString("MotionEstimationMethod_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaustive.
        /// </summary>
        public static string MotionEstimationMethod_Exhaustive {
            get {
                return ResourceManager.GetString("MotionEstimationMethod_Exhaustive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagon.
        /// </summary>
        public static string MotionEstimationMethod_Hexagon {
            get {
                return ResourceManager.GetString("MotionEstimationMethod_Hexagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformed Exhaustive.
        /// </summary>
        public static string MotionEstimationMethod_TransformedExhaustive {
            get {
                return ResourceManager.GetString("MotionEstimationMethod_TransformedExhaustive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneven Multi-Hexagon.
        /// </summary>
        public static string MotionEstimationMethod_UnevenMultiHexagon {
            get {
                return ResourceManager.GetString("MotionEstimationMethod_UnevenMultiHexagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Estimation Method:.
        /// </summary>
        public static string MotionEstimationMethodLabel {
            get {
                return ResourceManager.GetString("MotionEstimationMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Estimation Range:.
        /// </summary>
        public static string MotionEstimationRangeLabel {
            get {
                return ResourceManager.GetString("MotionEstimationRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DCT-Decimate:.
        /// </summary>
        public static string NoDctDecimateLabel {
            get {
                return ResourceManager.GetString("NoDctDecimateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string NoneCaption {
            get {
                return ResourceManager.GetString("NoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No tracks).
        /// </summary>
        public static string NoTracksPlaceholder {
            get {
                return ResourceManager.GetString("NoTracksPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options String.
        /// </summary>
        public static string OptionsString {
            get {
                return ResourceManager.GetString("OptionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Type:.
        /// </summary>
        public static string PartitionTypeLabel {
            get {
                return ResourceManager.GetString("PartitionTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC.
        /// </summary>
        public static string Passthrough_aac {
            get {
                return ResourceManager.GetString("Passthrough_aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC3.
        /// </summary>
        public static string Passthrough_ac3 {
            get {
                return ResourceManager.GetString("Passthrough_ac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Passthrough_any {
            get {
                return ResourceManager.GetString("Passthrough_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS.
        /// </summary>
        public static string Passthrough_dts {
            get {
                return ResourceManager.GetString("Passthrough_dts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS-HD.
        /// </summary>
        public static string Passthrough_dtshd {
            get {
                return ResourceManager.GetString("Passthrough_dtshd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        public static string Passthrough_mp3 {
            get {
                return ResourceManager.GetString("Passthrough_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which input codecs the passthrough will apply to..
        /// </summary>
        public static string PassthroughScopeToolTip {
            get {
                return ResourceManager.GetString("PassthroughScopeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Aspect Ratio:.
        /// </summary>
        public static string PixelAspectRatioLabel {
            get {
                return ResourceManager.GetString("PixelAspectRatioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually specify a Pixel Aspect Ratio..
        /// </summary>
        public static string PixelAspectRatioToolTip {
            get {
                return ResourceManager.GetString("PixelAspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Preset_Fast {
            get {
                return ResourceManager.GetString("Preset_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster.
        /// </summary>
        public static string Preset_Faster {
            get {
                return ResourceManager.GetString("Preset_Faster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (Default).
        /// </summary>
        public static string Preset_Medium {
            get {
                return ResourceManager.GetString("Preset_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placebo.
        /// </summary>
        public static string Preset_Placebo {
            get {
                return ResourceManager.GetString("Preset_Placebo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Preset_Slow {
            get {
                return ResourceManager.GetString("Preset_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower.
        /// </summary>
        public static string Preset_Slower {
            get {
                return ResourceManager.GetString("Preset_Slower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Fast.
        /// </summary>
        public static string Preset_SuperFast {
            get {
                return ResourceManager.GetString("Preset_SuperFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Fast.
        /// </summary>
        public static string Preset_UltraFast {
            get {
                return ResourceManager.GetString("Preset_UltraFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Fast.
        /// </summary>
        public static string Preset_VeryFast {
            get {
                return ResourceManager.GetString("Preset_VeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Slow.
        /// </summary>
        public static string Preset_VerySlow {
            get {
                return ResourceManager.GetString("Preset_VerySlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset:.
        /// </summary>
        public static string PresetLabel {
            get {
                return ResourceManager.GetString("PresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change options to trade off compression efficiency against encoding speed..
        /// </summary>
        public static string PresetToolTip {
            get {
                return ResourceManager.GetString("PresetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        public static string Profile_Baseline {
            get {
                return ResourceManager.GetString("Profile_Baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Profile_High {
            get {
                return ResourceManager.GetString("Profile_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High 4:4:4 Predictive.
        /// </summary>
        public static string Profile_High444 {
            get {
                return ResourceManager.GetString("Profile_High444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Profile_Main {
            get {
                return ResourceManager.GetString("Profile_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychovisual Rate Distortion:.
        /// </summary>
        public static string PsychoVisualRateDistortionLabel {
            get {
                return ResourceManager.GetString("PsychoVisualRateDistortionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychovisual Trellis:.
        /// </summary>
        public static string PsychovisualTrellisLabel {
            get {
                return ResourceManager.GetString("PsychovisualTrellisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PyramidalBFrames_Normal {
            get {
                return ResourceManager.GetString("PyramidalBFrames_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PyramidalBFrames_Off {
            get {
                return ResourceManager.GetString("PyramidalBFrames_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict.
        /// </summary>
        public static string PyramidalBFrames_Strict {
            get {
                return ResourceManager.GetString("PyramidalBFrames_Strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyramidal B-Frames:.
        /// </summary>
        public static string PyramidalBFramesLabel {
            get {
                return ResourceManager.GetString("PyramidalBFramesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSV Decoding.
        /// </summary>
        public static string QsvDecodingLabel {
            get {
                return ResourceManager.GetString("QsvDecodingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string QsvPreset_Balanced {
            get {
                return ResourceManager.GetString("QsvPreset_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QsvPreset_Quality {
            get {
                return ResourceManager.GetString("QsvPreset_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string QsvPreset_Speed {
            get {
                return ResourceManager.GetString("QsvPreset_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSV Preset:.
        /// </summary>
        public static string QsvPresetLabel {
            get {
                return ResourceManager.GetString("QsvPresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Frames:.
        /// </summary>
        public static string ReferenceFramesLabel {
            get {
                return ResourceManager.GetString("ReferenceFramesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove audio encoding.
        /// </summary>
        public static string RemoveAudioEncodingToolTip {
            get {
                return ResourceManager.GetString("RemoveAudioEncodingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as source.
        /// </summary>
        public static string SameAsSource {
            get {
                return ResourceManager.GetString("SameAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Rate.
        /// </summary>
        public static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Rate:.
        /// </summary>
        public static string SampleRateLabel {
            get {
                return ResourceManager.GetString("SampleRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicubic (OpenCL).
        /// </summary>
        public static string ScaleMethod_BicubicOpenCL {
            get {
                return ResourceManager.GetString("ScaleMethod_BicubicOpenCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        public static string ScaleMethod_Lanczos {
            get {
                return ResourceManager.GetString("ScaleMethod_Lanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos: This is the default scaler with the best quality.
        ///Bicubic: This is an OpenCL hardware accelerated scaling algorithm..
        /// </summary>
        public static string ScaleMethodToolTip {
            get {
                return ResourceManager.GetString("ScaleMethodToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope:.
        /// </summary>
        public static string ScopeLabel {
            get {
                return ResourceManager.GetString("ScopeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        public static string ShortFramerateLabel {
            get {
                return ResourceManager.GetString("ShortFramerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        public static string SizingLabel {
            get {
                return ResourceManager.GetString("SizingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Resolution:.
        /// </summary>
        public static string StorageResolutionLabel {
            get {
                return ResourceManager.GetString("StorageResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: SAD, no subpel (super fast!).
        /// </summary>
        public static string SubpixelMotionEstimation_0 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1: SAD, qpel.
        /// </summary>
        public static string SubpixelMotionEstimation_1 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10: QPRD in all frames.
        /// </summary>
        public static string SubpixelMotionEstimation_10 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11: No early terminations in analysis.
        /// </summary>
        public static string SubpixelMotionEstimation_11 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2: SATD, qpel.
        /// </summary>
        public static string SubpixelMotionEstimation_2 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3: SATD, multi-qpel.
        /// </summary>
        public static string SubpixelMotionEstimation_3 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4: SATD, qpel on all.
        /// </summary>
        public static string SubpixelMotionEstimation_4 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5: SATD, multi-qpel on all.
        /// </summary>
        public static string SubpixelMotionEstimation_5 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6: RD in I/P-frames.
        /// </summary>
        public static string SubpixelMotionEstimation_6 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7: RD in all frames.
        /// </summary>
        public static string SubpixelMotionEstimation_7 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8: RD refine in I/P-frames.
        /// </summary>
        public static string SubpixelMotionEstimation_8 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9: RD refine in all frames.
        /// </summary>
        public static string SubpixelMotionEstimation_9 {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimation_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subpixel Motion Estimation:.
        /// </summary>
        public static string SubpixelMotionEstimationLabel {
            get {
                return ResourceManager.GetString("SubpixelMotionEstimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Video.
        /// </summary>
        public static string TabHeader_Advanced {
            get {
                return ResourceManager.GetString("TabHeader_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string TabHeader_Audio {
            get {
                return ResourceManager.GetString("TabHeader_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string TabHeader_Picture {
            get {
                return ResourceManager.GetString("TabHeader_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TabHeader_Video {
            get {
                return ResourceManager.GetString("TabHeader_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Filters.
        /// </summary>
        public static string TabHeader_VideoFilters {
            get {
                return ResourceManager.GetString("TabHeader_VideoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Size (MB).
        /// </summary>
        public static string TargetSizeRadioButton {
            get {
                return ResourceManager.GetString("TargetSizeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Stream.
        /// </summary>
        public static string TargetStream {
            get {
                return ResourceManager.GetString("TargetStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string Trellis_Always {
            get {
                return ResourceManager.GetString("Trellis_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Only.
        /// </summary>
        public static string Trellis_EncodeOnly {
            get {
                return ResourceManager.GetString("Trellis_EncodeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Trellis_Off {
            get {
                return ResourceManager.GetString("Trellis_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trellis:.
        /// </summary>
        public static string TrellisLabel {
            get {
                return ResourceManager.GetString("TrellisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Tune_Animation {
            get {
                return ResourceManager.GetString("Tune_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Decode.
        /// </summary>
        public static string Tune_FastDecode {
            get {
                return ResourceManager.GetString("Tune_FastDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string Tune_Film {
            get {
                return ResourceManager.GetString("Tune_Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        public static string Tune_Grain {
            get {
                return ResourceManager.GetString("Tune_Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSNR.
        /// </summary>
        public static string Tune_Psnr {
            get {
                return ResourceManager.GetString("Tune_Psnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSIM.
        /// </summary>
        public static string Tune_Ssim {
            get {
                return ResourceManager.GetString("Tune_Ssim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still Image.
        /// </summary>
        public static string Tune_StillImage {
            get {
                return ResourceManager.GetString("Tune_StillImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Latency.
        /// </summary>
        public static string Tune_ZeroLatency {
            get {
                return ResourceManager.GetString("Tune_ZeroLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tune:.
        /// </summary>
        public static string TuneLabel {
            get {
                return ResourceManager.GetString("TuneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo first Pass.
        /// </summary>
        public static string TurboFirstPassCheckBox {
            get {
                return ResourceManager.GetString("TurboFirstPassCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-pass Encoding.
        /// </summary>
        public static string TwoPassEncodingCheckBox {
            get {
                return ResourceManager.GetString("TwoPassEncodingCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Framerate.
        /// </summary>
        public static string VfrChoice {
            get {
                return ResourceManager.GetString("VfrChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Framerate (VFR).
        /// </summary>
        public static string VfrPeakChoice {
            get {
                return ResourceManager.GetString("VfrPeakChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow a variable framerate and use the specified rate as a peak. If the source has a variable frame rate, this setting will preserve it. Note that some players do not support variable frame rates..
        /// </summary>
        public static string VfrPeakFramerateToolTip {
            get {
                return ResourceManager.GetString("VfrPeakFramerateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow a variable framerate. If the source has a variable frame rate, this setting will preserve it. Note that some players do not support variable frame rates..
        /// </summary>
        public static string VfrSameAsSourceToolTip {
            get {
                return ResourceManager.GetString("VfrSameAsSourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the desired quality factor. The scale used by each video encoder is different..
        /// </summary>
        public static string Video_QualityTargetToolTip {
            get {
                return ResourceManager.GetString("Video_QualityTargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Codec:.
        /// </summary>
        public static string VideoCodecLabel {
            get {
                return ResourceManager.GetString("VideoCodecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-2 (Libav).
        /// </summary>
        public static string VideoEncoder_ffmpeg2 {
            get {
                return ResourceManager.GetString("VideoEncoder_ffmpeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-4 (Libav).
        /// </summary>
        public static string VideoEncoder_ffmpeg4 {
            get {
                return ResourceManager.GetString("VideoEncoder_ffmpeg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-2.
        /// </summary>
        public static string VideoEncoder_mpeg2 {
            get {
                return ResourceManager.GetString("VideoEncoder_mpeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-4.
        /// </summary>
        public static string VideoEncoder_mpeg4 {
            get {
                return ResourceManager.GetString("VideoEncoder_mpeg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theora.
        /// </summary>
        public static string VideoEncoder_theora {
            get {
                return ResourceManager.GetString("VideoEncoder_theora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.264 (x264).
        /// </summary>
        public static string VideoEncoder_x264 {
            get {
                return ResourceManager.GetString("VideoEncoder_x264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web optimized.
        /// </summary>
        public static string WebOptimizedCheckBox {
            get {
                return ResourceManager.GetString("WebOptimizedCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange file to play better as a progressive download..
        /// </summary>
        public static string WebOptimizedToolTip {
            get {
                return ResourceManager.GetString("WebOptimizedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted P-Frames:.
        /// </summary>
        public static string WeightedPFramesLabel {
            get {
                return ResourceManager.GetString("WeightedPFramesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x264 Basic Settings.
        /// </summary>
        public static string X264BasicSettings {
            get {
                return ResourceManager.GetString("X264BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x264 Preset:.
        /// </summary>
        public static string X264PresetLabel {
            get {
                return ResourceManager.GetString("X264PresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change options to trade off compression efficiency against encoding speed. If you specify a preset, the changes it makes will be applied before all other parameters are applied..
        /// </summary>
        public static string X264PresetToolTip {
            get {
                return ResourceManager.GetString("X264PresetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the profile of the output stream. If you specify a profile, it overrides all other settings, so if you use it, you will be guaranteed a compatible stream.
        ///
        ///You should set this if you know your playback device only supports a certain profile..
        /// </summary>
        public static string X264ProfileToolTip {
            get {
                return ResourceManager.GetString("X264ProfileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x264 Settings.
        /// </summary>
        public static string X264Settings {
            get {
                return ResourceManager.GetString("X264Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Tab.
        /// </summary>
        public static string X264SettingsRadioButtonAdvanced {
            get {
                return ResourceManager.GetString("X264SettingsRadioButtonAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string X264SettingsRadioButtonBasic {
            get {
                return ResourceManager.GetString("X264SettingsRadioButtonBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x264 Tune:.
        /// </summary>
        public static string X264TuneLabel {
            get {
                return ResourceManager.GetString("X264TuneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tune options to further optimize them for your input content. If you specify a tuning, the changes will be applied after the Preset but before all other parameters..
        /// </summary>
        public static string X264TuneToolTip {
            get {
                return ResourceManager.GetString("X264TuneToolTip", resourceCulture);
            }
        }
    }
}
