//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources; 
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EncodingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncodingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.EncodingRes", typeof(EncodingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio encoding.
        /// </summary>
        public static string AddAudioEncodingButton {
            get {
                return ResourceManager.GetString("AddAudioEncodingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align A/V Start.
        /// </summary>
        public static string AlignAVStartCheckBox {
            get {
                return ResourceManager.GetString("AlignAVStartCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligns the initial timestamps of all audio and video streams by inserting blank frames or dropping frames. May improve audio/video sync for broken players that do not honor MP4 edit lists..
        /// </summary>
        public static string AlignAVStartCheckBoxToolTip {
            get {
                return ResourceManager.GetString("AlignAVStartCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Anamorphic.
        /// </summary>
        public static string AnamorphicCheckbox {
            get {
                return ResourceManager.GetString("AnamorphicCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Anamorphic enabled, non-square pixels are allowed. This can result in more efficient storage, but not all players support this..
        /// </summary>
        public static string AnamorphicToolTip {
            get {
                return ResourceManager.GetString("AnamorphicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to queue.
        /// </summary>
        public static string ApplyToQueueButton {
            get {
                return ResourceManager.GetString("ApplyToQueueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High values mean high compression: better quality/smaller size but longer encode times..
        /// </summary>
        public static string AscendingCompressionToolTip {
            get {
                return ResourceManager.GetString("AscendingCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High values mean high quality..
        /// </summary>
        public static string AscendingQualityToolTip {
            get {
                return ResourceManager.GetString("AscendingQualityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Range Compression. Valid values are 0-4.
        ///
        ///For source audio that has a wide dynamic range (very loud and very soft sequences), DRC allows you to &quot;compress&quot; the range by making loud sections softer and soft sections louder.
        ///
        ///This only works with AC3 sources..
        /// </summary>
        public static string Audio_DrcToolTip {
            get {
                return ResourceManager.GetString("Audio_DrcToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplify or attenuate audio before encoding. Valid values are -20 to +20 dB..
        /// </summary>
        public static string Audio_GainToolTip {
            get {
                return ResourceManager.GetString("Audio_GainToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of compression to apply. {0} Valid values are from {1} to {2}..
        /// </summary>
        public static string AudioCompressionToolTip {
            get {
                return ResourceManager.GetString("AudioCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC3.
        /// </summary>
        public static string AudioEncoder_ac3 {
            get {
                return ResourceManager.GetString("AudioEncoder_ac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC (avcodec).
        /// </summary>
        public static string AudioEncoder_av_aac {
            get {
                return ResourceManager.GetString("AudioEncoder_av_aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC (FAAC).
        /// </summary>
        public static string AudioEncoder_faac {
            get {
                return ResourceManager.GetString("AudioEncoder_faac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC 16-bit.
        /// </summary>
        public static string AudioEncoder_flac16 {
            get {
                return ResourceManager.GetString("AudioEncoder_flac16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC 24-bit.
        /// </summary>
        public static string AudioEncoder_flac24 {
            get {
                return ResourceManager.GetString("AudioEncoder_flac24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        public static string AudioEncoder_mp3 {
            get {
                return ResourceManager.GetString("AudioEncoder_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AudioEncoder_none {
            get {
                return ResourceManager.GetString("AudioEncoder_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough.
        /// </summary>
        public static string AudioEncoder_Passthrough {
            get {
                return ResourceManager.GetString("AudioEncoder_Passthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis.
        /// </summary>
        public static string AudioEncoder_vorbis {
            get {
                return ResourceManager.GetString("AudioEncoder_vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio quality target. {0} Valid values are from {1} to {2}..
        /// </summary>
        public static string AudioQualityToolTip {
            get {
                return ResourceManager.GetString("AudioQualityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (auto).
        /// </summary>
        public static string AutoCaption {
            get {
                return ResourceManager.GetString("AutoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback:.
        /// </summary>
        public static string AutoPassthroughFallbackLabel {
            get {
                return ResourceManager.GetString("AutoPassthroughFallbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough does not work on all audio codecs. This specifies the encoder to fall back to if the track cannot be passed through..
        /// </summary>
        public static string AutoPassthroughFallbackToolTip {
            get {
                return ResourceManager.GetString("AutoPassthroughFallbackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg bitrate (kbps).
        /// </summary>
        public static string AverageBitrateRadioButton {
            get {
                return ResourceManager.GetString("AverageBitrateRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string Bitrate {
            get {
                return ResourceManager.GetString("Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate:.
        /// </summary>
        public static string BitrateLabel {
            get {
                return ResourceManager.GetString("BitrateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot switch encoding preset, it has been locked in the Picker window..
        /// </summary>
        public static string CannotSwitchEncodingPresetDueToPicker {
            get {
                return ResourceManager.GetString("CannotSwitchEncodingPresetDueToPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the listed framerate from the source title for a constant framerate..
        /// </summary>
        public static string CfrSameAsSourceToolTip {
            get {
                return ResourceManager.GetString("CfrSameAsSourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a constant frame rate..
        /// </summary>
        public static string CfrToolTip {
            get {
                return ResourceManager.GetString("CfrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Layout.
        /// </summary>
        public static string ChannelLayout {
            get {
                return ResourceManager.GetString("ChannelLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a name for the subfolder:.
        /// </summary>
        public static string ChooseNameSubfolder {
            get {
                return ResourceManager.GetString("ChooseNameSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new name for the folder:.
        /// </summary>
        public static string ChooseNewFolderName {
            get {
                return ResourceManager.GetString("ChooseNewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma smooth:.
        /// </summary>
        public static string ChromaSmoothLabel {
            get {
                return ResourceManager.GetString("ChromaSmoothLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces chroma noise, rainbows, and other prominent visual artifacts. Useful for resolving various color-related issues, especially with lower resolution content from analog sources, e.g. poor quality DVD and VHS sources. The blurring/smoothing algorithm is the same as used by the unsharp filter..
        /// </summary>
        public static string ChromaSmoothToolTip {
            get {
                return ResourceManager.GetString("ChromaSmoothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the presets list.
        /// </summary>
        public static string ClosePresetsListToolTip {
            get {
                return ResourceManager.GetString("ClosePresetsListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        public static string CodecLabel {
            get {
                return ResourceManager.GetString("CodecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorspace:.
        /// </summary>
        public static string ColorspaceLabel {
            get {
                return ResourceManager.GetString("ColorspaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant framerate.
        /// </summary>
        public static string ConstantFramerateRadioButton {
            get {
                return ResourceManager.GetString("ConstantFramerateRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant quality.
        /// </summary>
        public static string ConstantQualityRadioButton {
            get {
                return ResourceManager.GetString("ConstantQualityRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain to one axis.
        /// </summary>
        public static string ConstrainToOneAxisCheckBox {
            get {
                return ResourceManager.GetString("ConstrainToOneAxisCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, only the axis with the most total detected cropping will be cropped. For example if Top+Bottom = 32 and Left+Right = 6, then cropping on Left and Right will be set to 0..
        /// </summary>
        public static string ConstrainToOneAxisToolTip {
            get {
                return ResourceManager.GetString("ConstrainToOneAxisToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container format:.
        /// </summary>
        public static string ContainerLabel {
            get {
                return ResourceManager.GetString("ContainerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropping.
        /// </summary>
        public static string CroppingLabel {
            get {
                return ResourceManager.GetString("CroppingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservative.
        /// </summary>
        public static string CroppingType_Conservative {
            get {
                return ResourceManager.GetString("CroppingType_Conservative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: key1=value1:key2=value2:....
        /// </summary>
        public static string CustomFilterToolTipFormatPart {
            get {
                return ResourceManager.GetString("CustomFilterToolTipFormatPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys:.
        /// </summary>
        public static string CustomFilterToolTipKeysLabel {
            get {
                return ResourceManager.GetString("CustomFilterToolTipKeysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deblock:.
        /// </summary>
        public static string DeblockLabel {
            get {
                return ResourceManager.GetString("DeblockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deblock reduces blocky artifacts caused by low quality video compression..
        /// </summary>
        public static string DeblockToolTip {
            get {
                return ResourceManager.GetString("DeblockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter {0}.
        /// </summary>
        public static string DefaultChapterName {
            get {
                return ResourceManager.GetString("DefaultChapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Default).
        /// </summary>
        public static string DefaultFormat {
            get {
                return ResourceManager.GetString("DefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string DefaultPresetFolderName {
            get {
                return ResourceManager.GetString("DefaultPresetFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterlace:.
        /// </summary>
        public static string DeinterlaceLabel {
            get {
                return ResourceManager.GetString("DeinterlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterlace removes comb artifacts from the picture.
        ///
        ///Bwdif and Yadif are two popular and fast deinterlacers.
        ///
        ///Decomb switches between multiple interpolation algorithms for speed and quality..
        /// </summary>
        public static string DeinterlaceToolTip {
            get {
                return ResourceManager.GetString("DeinterlaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoise:.
        /// </summary>
        public static string DenoiseLabel {
            get {
                return ResourceManager.GetString("DenoiseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoise reduces or removes the appearance of noise and grain. This can improve compression efficiency and create higher quality video at smaller file sizes. 
        ///Overly strong Denoise settings may damage picture quality by discarding detail.
        ///         
        ///NLMeans is a high quality denoise filter with a cost to speed. Use where quality is more important than speed.
        ///         
        ///HQDN3D is an adaptive low-pass filter, faster than NLMeans but less effective at preserving fine detail..
        /// </summary>
        public static string DenoiseToolTip {
            get {
                return ResourceManager.GetString("DenoiseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low values mean high compression: better quality/smaller size but longer encode times..
        /// </summary>
        public static string DescendingCompressionToolTip {
            get {
                return ResourceManager.GetString("DescendingCompressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low values mean high quality..
        /// </summary>
        public static string DescendingQualityToolTip {
            get {
                return ResourceManager.GetString("DescendingQualityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detelecine:.
        /// </summary>
        public static string DetelecineLabel {
            get {
                return ResourceManager.GetString("DetelecineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter removes &apos;combing&apos; artifacts that are the result of telecining.
        ///
        ///Telecining is a process that adjusts film framerates that are 24fps to NTSC video frame rates which are 30fps..
        /// </summary>
        public static string DetelecineToolTip {
            get {
                return ResourceManager.GetString("DetelecineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display resolution:.
        /// </summary>
        public static string DisplayResolutionLabel {
            get {
                return ResourceManager.GetString("DisplayResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRC:.
        /// </summary>
        public static string DrcLabel {
            get {
                return ResourceManager.GetString("DrcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder.
        /// </summary>
        public static string Encoder {
            get {
                return ResourceManager.GetString("Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder settings.
        /// </summary>
        public static string EncoderSettings {
            get {
                return ResourceManager.GetString("EncoderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension:.
        /// </summary>
        public static string ExtensionLabel {
            get {
                return ResourceManager.GetString("ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip horizontally.
        /// </summary>
        public static string FlipHorizontalCheckBox {
            get {
                return ResourceManager.GetString("FlipHorizontalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the picture horizontally. This is applied before any rotation..
        /// </summary>
        public static string FlipHorizontalToolTip {
            get {
                return ResourceManager.GetString("FlipHorizontalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vertically.
        /// </summary>
        public static string FlipVerticalCheckBox {
            get {
                return ResourceManager.GetString("FlipVerticalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the picture vertically. This is applied before any rotation..
        /// </summary>
        public static string FlipVerticalToolTip {
            get {
                return ResourceManager.GetString("FlipVerticalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.###} FPS.
        /// </summary>
        public static string FpsFormat {
            get {
                return ResourceManager.GetString("FpsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate (FPS):.
        /// </summary>
        public static string FramerateLabel {
            get {
                return ResourceManager.GetString("FramerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full parameter list:.
        /// </summary>
        public static string FullEncoderParameterLabel {
            get {
                return ResourceManager.GetString("FullEncoderParameterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain (dB):.
        /// </summary>
        public static string GainLabel {
            get {
                return ResourceManager.GetString("GainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale encoding.
        /// </summary>
        public static string GrayscaleCheckBox {
            get {
                return ResourceManager.GetString("GrayscaleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality.
        /// </summary>
        public static string HighQuality {
            get {
                return ResourceManager.GetString("HighQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include chapter markers.
        /// </summary>
        public static string IncludeChapterMarkersCheckBox {
            get {
                return ResourceManager.GetString("IncludeChapterMarkersCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include chapter markers from the input video in the encoded video..
        /// </summary>
        public static string IncludeChapterMarkersToolTip {
            get {
                return ResourceManager.GetString("IncludeChapterMarkersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlace Detection:.
        /// </summary>
        public static string InterlaceDetectionLabel {
            get {
                return ResourceManager.GetString("InterlaceDetectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod 5G support.
        /// </summary>
        public static string Ipod5GSupportCheckBox {
            get {
                return ResourceManager.GetString("Ipod5GSupportCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a marker to the file that older iPods require before they&apos;ll allow H.264 video to sync..
        /// </summary>
        public static string IPod5GSupportToolTip {
            get {
                return ResourceManager.GetString("IPod5GSupportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets and ensures compliance with the specified encoder level.
        ///
        ///Overrides all other settings..
        /// </summary>
        public static string LevelToolTip {
            get {
                return ResourceManager.GetString("LevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low quality.
        /// </summary>
        public static string LowQuality {
            get {
                return ResourceManager.GetString("LowQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height:.
        /// </summary>
        public static string MaxHeightLabel {
            get {
                return ResourceManager.GetString("MaxHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width:.
        /// </summary>
        public static string MaxWidthLabel {
            get {
                return ResourceManager.GetString("MaxWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum:.
        /// </summary>
        public static string MinimumCroppingLabel {
            get {
                return ResourceManager.GetString("MinimumCroppingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the automatic cropping is below this amount for a side, disable the cropping for that side. Useful for preventing resampling on small cropping amounts..
        /// </summary>
        public static string MinimumCroppingToolTip {
            get {
                return ResourceManager.GetString("MinimumCroppingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.1 (5F/2R/LFE).
        /// </summary>
        public static string Mixdown_5_2_lfe {
            get {
                return ResourceManager.GetString("Mixdown_5_2_lfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1 Channels.
        /// </summary>
        public static string Mixdown_5point1 {
            get {
                return ResourceManager.GetString("Mixdown_5point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Surround.
        /// </summary>
        public static string Mixdown_dpl1 {
            get {
                return ResourceManager.GetString("Mixdown_dpl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Pro Logic II.
        /// </summary>
        public static string Mixdown_dpl2 {
            get {
                return ResourceManager.GetString("Mixdown_dpl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono (Left Only).
        /// </summary>
        public static string Mixdown_left_only {
            get {
                return ResourceManager.GetString("Mixdown_left_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string Mixdown_mono {
            get {
                return ResourceManager.GetString("Mixdown_mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono (Right Only).
        /// </summary>
        public static string Mixdown_right_only {
            get {
                return ResourceManager.GetString("Mixdown_right_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string Mixdown_stereo {
            get {
                return ResourceManager.GetString("Mixdown_stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixdown:.
        /// </summary>
        public static string MixdownLabel {
            get {
                return ResourceManager.GetString("MixdownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string ModeLabel {
            get {
                return ResourceManager.GetString("ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional advanced arguments to pass to the video encoder..
        /// </summary>
        public static string MoreOptionsToolTip {
            get {
                return ResourceManager.GetString("MoreOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More settings:.
        /// </summary>
        public static string MoreSettingsLabel {
            get {
                return ResourceManager.GetString("MoreSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string NoneCaption {
            get {
                return ResourceManager.GetString("NoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No tracks).
        /// </summary>
        public static string NoTracksPlaceholder {
            get {
                return ResourceManager.GetString("NoTracksPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance.
        /// </summary>
        public static string NVEncPreset_hp {
            get {
                return ResourceManager.GetString("NVEncPreset_hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality.
        /// </summary>
        public static string NVEncPreset_hq {
            get {
                return ResourceManager.GetString("NVEncPreset_hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Latency.
        /// </summary>
        public static string NVEncPreset_ll {
            get {
                return ResourceManager.GetString("NVEncPreset_ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the presets list.
        /// </summary>
        public static string OpenPresetsListToolTip {
            get {
                return ResourceManager.GetString("OpenPresetsListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string PadColorLabel {
            get {
                return ResourceManager.GetString("PadColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: FFFFFF.
        /// </summary>
        public static string PadColorTextToolTip {
            get {
                return ResourceManager.GetString("PadColorTextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        public static string PaddingLabel {
            get {
                return ResourceManager.GetString("PaddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string PaddingMode_Fill {
            get {
                return ResourceManager.GetString("PaddingMode_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string PaddingMode_Height {
            get {
                return ResourceManager.GetString("PaddingMode_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string PaddingMode_Width {
            get {
                return ResourceManager.GetString("PaddingMode_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC.
        /// </summary>
        public static string Passthrough_aac {
            get {
                return ResourceManager.GetString("Passthrough_aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC3.
        /// </summary>
        public static string Passthrough_ac3 {
            get {
                return ResourceManager.GetString("Passthrough_ac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Passthrough_auto {
            get {
                return ResourceManager.GetString("Passthrough_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS.
        /// </summary>
        public static string Passthrough_dts {
            get {
                return ResourceManager.GetString("Passthrough_dts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS-HD.
        /// </summary>
        public static string Passthrough_dtshd {
            get {
                return ResourceManager.GetString("Passthrough_dtshd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-AC3.
        /// </summary>
        public static string Passthrough_eac3 {
            get {
                return ResourceManager.GetString("Passthrough_eac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC.
        /// </summary>
        public static string Passthrough_flac {
            get {
                return ResourceManager.GetString("Passthrough_flac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        public static string Passthrough_mp3 {
            get {
                return ResourceManager.GetString("Passthrough_mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueHD.
        /// </summary>
        public static string Passthrough_truehd {
            get {
                return ResourceManager.GetString("Passthrough_truehd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough if possible.
        /// </summary>
        public static string PassthroughIfPossibleCheckBox {
            get {
                return ResourceManager.GetString("PassthroughIfPossibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the input track matches the codec it will be passed through instead of encoded..
        /// </summary>
        public static string PassthroughIfPossibleToolTip {
            get {
                return ResourceManager.GetString("PassthroughIfPossibleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow passthrough for:.
        /// </summary>
        public static string PassthroughMaskLabel {
            get {
                return ResourceManager.GetString("PassthroughMaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which input codecs the passthrough will apply to..
        /// </summary>
        public static string PassthroughScopeToolTip {
            get {
                return ResourceManager.GetString("PassthroughScopeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough settings.
        /// </summary>
        public static string PassthroughSettingsLabel {
            get {
                return ResourceManager.GetString("PassthroughSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel aspect ratio denominator.
        /// </summary>
        public static string PixelAspectRatioDenominatorAutomationName {
            get {
                return ResourceManager.GetString("PixelAspectRatioDenominatorAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel aspect ratio:.
        /// </summary>
        public static string PixelAspectRatioLabel {
            get {
                return ResourceManager.GetString("PixelAspectRatioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel aspect ratio numerator.
        /// </summary>
        public static string PixelAspectRatioNumeratorAutomationName {
            get {
                return ResourceManager.GetString("PixelAspectRatioNumeratorAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually specify a Pixel Aspect Ratio..
        /// </summary>
        public static string PixelAspectRatioToolTip {
            get {
                return ResourceManager.GetString("PixelAspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Preset_Fast {
            get {
                return ResourceManager.GetString("Preset_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster.
        /// </summary>
        public static string Preset_Faster {
            get {
                return ResourceManager.GetString("Preset_Faster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Preset_Medium {
            get {
                return ResourceManager.GetString("Preset_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placebo.
        /// </summary>
        public static string Preset_Placebo {
            get {
                return ResourceManager.GetString("Preset_Placebo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Preset_Slow {
            get {
                return ResourceManager.GetString("Preset_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower.
        /// </summary>
        public static string Preset_Slower {
            get {
                return ResourceManager.GetString("Preset_Slower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super fast.
        /// </summary>
        public static string Preset_SuperFast {
            get {
                return ResourceManager.GetString("Preset_SuperFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra fast.
        /// </summary>
        public static string Preset_UltraFast {
            get {
                return ResourceManager.GetString("Preset_UltraFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very fast.
        /// </summary>
        public static string Preset_VeryFast {
            get {
                return ResourceManager.GetString("Preset_VeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very slow.
        /// </summary>
        public static string Preset_VerySlow {
            get {
                return ResourceManager.GetString("Preset_VerySlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        public static string PresetFolder_BuiltIn {
            get {
                return ResourceManager.GetString("PresetFolder_BuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string PresetFolder_Custom {
            get {
                return ResourceManager.GetString("PresetFolder_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create subfolder.
        /// </summary>
        public static string PresetFolderCreateSubfolderMenuItem {
            get {
                return ResourceManager.GetString("PresetFolderCreateSubfolderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder.
        /// </summary>
        public static string PresetFolderRemoveFolderMenuItem {
            get {
                return ResourceManager.GetString("PresetFolderRemoveFolderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset:.
        /// </summary>
        public static string PresetLabel {
            get {
                return ResourceManager.GetString("PresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change options to trade off compression efficiency against encoding speed..
        /// </summary>
        public static string PresetToolTip {
            get {
                return ResourceManager.GetString("PresetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        public static string PrestFolderRenameFolderMenuItem {
            get {
                return ResourceManager.GetString("PrestFolderRenameFolderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        public static string Profile_baseline {
            get {
                return ResourceManager.GetString("Profile_baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Profile_high {
            get {
                return ResourceManager.GetString("Profile_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High 4:4:4 Predictive.
        /// </summary>
        public static string Profile_high444 {
            get {
                return ResourceManager.GetString("Profile_high444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Profile_main {
            get {
                return ResourceManager.GetString("Profile_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the profile of the output stream. If you specify a profile, it overrides all other settings, so if you use it, you will be guaranteed a compatible stream.
        ///
        ///You should set this if you know your playback device only supports a certain profile..
        /// </summary>
        public static string ProfileToolTip {
            get {
                return ResourceManager.GetString("ProfileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSV Decoding.
        /// </summary>
        public static string QsvDecodingLabel {
            get {
                return ResourceManager.GetString("QsvDecodingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string QsvPreset_Balanced {
            get {
                return ResourceManager.GetString("QsvPreset_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QsvPreset_Quality {
            get {
                return ResourceManager.GetString("QsvPreset_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string QsvPreset_Speed {
            get {
                return ResourceManager.GetString("QsvPreset_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove audio encoding.
        /// </summary>
        public static string RemoveAudioEncodingToolTip {
            get {
                return ResourceManager.GetString("RemoveAudioEncodingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180°.
        /// </summary>
        public static string Rotation_180 {
            get {
                return ResourceManager.GetString("Rotation_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise 90°.
        /// </summary>
        public static string Rotation_Clockwise90 {
            get {
                return ResourceManager.GetString("Rotation_Clockwise90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise 90°.
        /// </summary>
        public static string Rotation_Counterclockwise90 {
            get {
                return ResourceManager.GetString("Rotation_Counterclockwise90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string RotationLabel {
            get {
                return ResourceManager.GetString("RotationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the picture. This is applied after all sizing and cropping..
        /// </summary>
        public static string RotationToolTip {
            get {
                return ResourceManager.GetString("RotationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as source.
        /// </summary>
        public static string SameAsSource {
            get {
                return ResourceManager.GetString("SameAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate.
        /// </summary>
        public static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate:.
        /// </summary>
        public static string SampleRateLabel {
            get {
                return ResourceManager.GetString("SampleRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicubic (OpenCL).
        /// </summary>
        public static string ScaleMethod_BicubicOpenCL {
            get {
                return ResourceManager.GetString("ScaleMethod_BicubicOpenCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        public static string ScaleMethod_Lanczos {
            get {
                return ResourceManager.GetString("ScaleMethod_Lanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downscale only.
        /// </summary>
        public static string ScalingMode_DownscaleOnly {
            get {
                return ResourceManager.GetString("ScalingMode_DownscaleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale up/down to target.
        /// </summary>
        public static string ScalingMode_Fill {
            get {
                return ResourceManager.GetString("ScalingMode_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling mode:.
        /// </summary>
        public static string ScalingModeLabel {
            get {
                return ResourceManager.GetString("ScalingModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        public static string SharpenLabel {
            get {
                return ResourceManager.GetString("SharpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpening enhances the appearance of detail, especially edges. Overly strong Sharpen settings may damage picture quality by creating ringing artifacts and enhancing noise, which can reduce compression efficiency.
        ///
        ///Unsharp is a general purpose unsharp masking filter. It sharpens by blurring, then calculating the difference between the blurred picture and the original.
        ///
        ///Lapsharp sharpens using convolution kernels approximating Laplacian edge filters, sometimes producing higher quality results than unshar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SharpenToolTip {
            get {
                return ResourceManager.GetString("SharpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        public static string ShortFramerateLabel {
            get {
                return ResourceManager.GetString("ShortFramerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        public static string SizingLabel {
            get {
                return ResourceManager.GetString("SizingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string SizingModeManual {
            get {
                return ResourceManager.GetString("SizingModeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic will pick the size for you based on provided constraints. Manual will let you enter a specific size and pixel aspect ratio..
        /// </summary>
        public static string SizingModeToolTip {
            get {
                return ResourceManager.GetString("SizingModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage resolution:.
        /// </summary>
        public static string StorageResolutionLabel {
            get {
                return ResourceManager.GetString("StorageResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Encoding.
        /// </summary>
        public static string TabHeader_AudioEncoding {
            get {
                return ResourceManager.GetString("TabHeader_AudioEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string TabHeader_Container {
            get {
                return ResourceManager.GetString("TabHeader_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        public static string TabHeader_Sizing {
            get {
                return ResourceManager.GetString("TabHeader_Sizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Encoding.
        /// </summary>
        public static string TabHeader_VideoEncoding {
            get {
                return ResourceManager.GetString("TabHeader_VideoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Filters.
        /// </summary>
        public static string TabHeader_VideoFilters {
            get {
                return ResourceManager.GetString("TabHeader_VideoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target height:.
        /// </summary>
        public static string TargetHeightLabel {
            get {
                return ResourceManager.GetString("TargetHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target size (MB).
        /// </summary>
        public static string TargetSizeRadioButton {
            get {
                return ResourceManager.GetString("TargetSizeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target stream.
        /// </summary>
        public static string TargetStream {
            get {
                return ResourceManager.GetString("TargetStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target width:.
        /// </summary>
        public static string TargetWidthLabel {
            get {
                return ResourceManager.GetString("TargetWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Tune_animation {
            get {
                return ResourceManager.GetString("Tune_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast decode.
        /// </summary>
        public static string Tune_fastdecode {
            get {
                return ResourceManager.GetString("Tune_fastdecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string Tune_film {
            get {
                return ResourceManager.GetString("Tune_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        public static string Tune_grain {
            get {
                return ResourceManager.GetString("Tune_grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSNR.
        /// </summary>
        public static string Tune_psnr {
            get {
                return ResourceManager.GetString("Tune_psnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSIM.
        /// </summary>
        public static string Tune_ssim {
            get {
                return ResourceManager.GetString("Tune_ssim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still image.
        /// </summary>
        public static string Tune_stillimage {
            get {
                return ResourceManager.GetString("Tune_stillimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero latency.
        /// </summary>
        public static string Tune_zerolatency {
            get {
                return ResourceManager.GetString("Tune_zerolatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tune:.
        /// </summary>
        public static string TuneLabel {
            get {
                return ResourceManager.GetString("TuneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo first pass.
        /// </summary>
        public static string TurboFirstPassCheckBox {
            get {
                return ResourceManager.GetString("TurboFirstPassCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-pass encoding.
        /// </summary>
        public static string TwoPassEncodingCheckBox {
            get {
                return ResourceManager.GetString("TwoPassEncodingCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscale {0}x max.
        /// </summary>
        public static string UpscaleMaxFormat {
            get {
                return ResourceManager.GetString("UpscaleMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable framerate.
        /// </summary>
        public static string VfrChoice {
            get {
                return ResourceManager.GetString("VfrChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak framerate (VFR).
        /// </summary>
        public static string VfrPeakChoice {
            get {
                return ResourceManager.GetString("VfrPeakChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow a variable framerate and use the specified rate as a peak. If the source has a variable frame rate, this setting will preserve it. Note that some players do not support variable frame rates..
        /// </summary>
        public static string VfrPeakFramerateToolTip {
            get {
                return ResourceManager.GetString("VfrPeakFramerateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow a variable framerate. If the source has a variable frame rate, this setting will preserve it. Note that some players do not support variable frame rates..
        /// </summary>
        public static string VfrSameAsSourceToolTip {
            get {
                return ResourceManager.GetString("VfrSameAsSourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the desired quality factor. The scale used by each video encoder is different..
        /// </summary>
        public static string Video_QualityTargetToolTip {
            get {
                return ResourceManager.GetString("Video_QualityTargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video codec:.
        /// </summary>
        public static string VideoCodecLabel {
            get {
                return ResourceManager.GetString("VideoCodecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-2 (Libav).
        /// </summary>
        public static string VideoEncoder_ffmpeg2 {
            get {
                return ResourceManager.GetString("VideoEncoder_ffmpeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-4 (Libav).
        /// </summary>
        public static string VideoEncoder_ffmpeg4 {
            get {
                return ResourceManager.GetString("VideoEncoder_ffmpeg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-2.
        /// </summary>
        public static string VideoEncoder_mpeg2 {
            get {
                return ResourceManager.GetString("VideoEncoder_mpeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG-4.
        /// </summary>
        public static string VideoEncoder_mpeg4 {
            get {
                return ResourceManager.GetString("VideoEncoder_mpeg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theora.
        /// </summary>
        public static string VideoEncoder_theora {
            get {
                return ResourceManager.GetString("VideoEncoder_theora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.264 (x264).
        /// </summary>
        public static string VideoEncoder_x264 {
            get {
                return ResourceManager.GetString("VideoEncoder_x264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web optimized.
        /// </summary>
        public static string WebOptimizedCheckBox {
            get {
                return ResourceManager.GetString("WebOptimizedCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange file to play better as a progressive download..
        /// </summary>
        public static string WebOptimizedToolTip {
            get {
                return ResourceManager.GetString("WebOptimizedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding preset: {0}.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tune options to further optimize them for your input content. If you specify a tuning, the changes will be applied after the Preset but before all other parameters..
        /// </summary>
        public static string X264TuneToolTip {
            get {
                return ResourceManager.GetString("X264TuneToolTip", resourceCulture);
            }
        }
    }
