//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources; 
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.EnumsRes", typeof(EnumsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Anamorphic_Custom {
            get {
                return ResourceManager.GetString("Anamorphic_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose.
        /// </summary>
        public static string Anamorphic_Loose {
            get {
                return ResourceManager.GetString("Anamorphic_Loose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Anamorphic_None {
            get {
                return ResourceManager.GetString("Anamorphic_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict.
        /// </summary>
        public static string Anamorphic_Strict {
            get {
                return ResourceManager.GetString("Anamorphic_Strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use OS theme.
        /// </summary>
        public static string AppThemeChoice_Auto {
            get {
                return ResourceManager.GetString("AppThemeChoice_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string AppThemeChoice_Dark {
            get {
                return ResourceManager.GetString("AppThemeChoice_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string AppThemeChoice_Light {
            get {
                return ResourceManager.GetString("AppThemeChoice_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string CombDetect_fast {
            get {
                return ResourceManager.GetString("CombDetect_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Sensitive.
        /// </summary>
        public static string CombDetect_permissive {
            get {
                return ResourceManager.GetString("CombDetect_permissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string Decomb_Bob {
            get {
                return ResourceManager.GetString("Decomb_Bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Decomb_Fast {
            get {
                return ResourceManager.GetString("Decomb_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bwdif.
        /// </summary>
        public static string Deinterlace_Bwdif {
            get {
                return ResourceManager.GetString("Deinterlace_Bwdif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decomb.
        /// </summary>
        public static string Deinterlace_Decomb {
            get {
                return ResourceManager.GetString("Deinterlace_Decomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadif.
        /// </summary>
        public static string Deinterlace_Yadif {
            get {
                return ResourceManager.GetString("Deinterlace_Yadif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string DeinterlacePreset_bob {
            get {
                return ResourceManager.GetString("DeinterlacePreset_bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEDI2.
        /// </summary>
        public static string DeinterlacePreset_eedi2 {
            get {
                return ResourceManager.GetString("DeinterlacePreset_eedi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEDI2 Bob.
        /// </summary>
        public static string DeinterlacePreset_eedi2bob {
            get {
                return ResourceManager.GetString("DeinterlacePreset_eedi2bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Spatial Check.
        /// </summary>
        public static string DeinterlacePreset_skipspatial {
            get {
                return ResourceManager.GetString("DeinterlacePreset_skipspatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma smooth.
        /// </summary>
        public static string Denoise_ChromaSmooth {
            get {
                return ResourceManager.GetString("Denoise_ChromaSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hqdn3d.
        /// </summary>
        public static string Denoise_HQDN3D {
            get {
                return ResourceManager.GetString("Denoise_HQDN3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL-Means.
        /// </summary>
        public static string Denoise_NLMeans {
            get {
                return ResourceManager.GetString("Denoise_NLMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string DenoisePreset_light {
            get {
                return ResourceManager.GetString("DenoisePreset_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DenoisePreset_medium {
            get {
                return ResourceManager.GetString("DenoisePreset_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string DenoisePreset_strong {
            get {
                return ResourceManager.GetString("DenoisePreset_strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultralight.
        /// </summary>
        public static string DenoisePreset_ultralight {
            get {
                return ResourceManager.GetString("DenoisePreset_ultralight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string DenoiseTune_animation {
            get {
                return ResourceManager.GetString("DenoiseTune_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string DenoiseTune_film {
            get {
                return ResourceManager.GetString("DenoiseTune_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        public static string DenoiseTune_grain {
            get {
                return ResourceManager.GetString("DenoiseTune_grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Motion.
        /// </summary>
        public static string DenoiseTune_highmotion {
            get {
                return ResourceManager.GetString("DenoiseTune_highmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DenoiseTune_medium {
            get {
                return ResourceManager.GetString("DenoiseTune_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DenoiseTune_none {
            get {
                return ResourceManager.GetString("DenoiseTune_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string DenoiseTune_small {
            get {
                return ResourceManager.GetString("DenoiseTune_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        public static string DenoiseTune_tiny {
            get {
                return ResourceManager.GetString("DenoiseTune_tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very wide.
        /// </summary>
        public static string DenoiseTune_verywide {
            get {
                return ResourceManager.GetString("DenoiseTune_verywide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        public static string DenoiseTune_wide {
            get {
                return ResourceManager.GetString("DenoiseTune_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        public static string DragDropOrder_Alphabetical {
            get {
                return ResourceManager.GetString("DragDropOrder_Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string DragDropOrder_Selected {
            get {
                return ResourceManager.GetString("DragDropOrder_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close VidCoder.
        /// </summary>
        public static string EncodeCompleteActionType_CloseProgram {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_CloseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string EncodeCompleteActionType_DoNothing {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject {0}:.
        /// </summary>
        public static string EncodeCompleteActionType_EjectDisc {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_EjectDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        public static string EncodeCompleteActionType_Hibernate {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string EncodeCompleteActionType_LogOff {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down.
        /// </summary>
        public static string EncodeCompleteActionType_Shutdown {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string EncodeCompleteActionType_Sleep {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop encoding.
        /// </summary>
        public static string EncodeCompleteActionType_StopEncoding {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_StopEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string LogOperationType_Encode {
            get {
                return ResourceManager.GetString("LogOperationType_Encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string LogOperationType_Scan {
            get {
                return ResourceManager.GetString("LogOperationType_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string PickerTimeRangeMode_Chapters {
            get {
                return ResourceManager.GetString("PickerTimeRangeMode_Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range.
        /// </summary>
        public static string PickerTimeRangeMode_Time {
            get {
                return ResourceManager.GetString("PickerTimeRangeMode_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LapSharp.
        /// </summary>
        public static string Sharpen_LapSharp {
            get {
                return ResourceManager.GetString("Sharpen_LapSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSharp.
        /// </summary>
        public static string Sharpen_UnSharp {
            get {
                return ResourceManager.GetString("Sharpen_UnSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Delete (IRREVERSIBLE) ⚠️.
        /// </summary>
        public static string SourceFileRemoval_Delete {
            get {
                return ResourceManager.GetString("SourceFileRemoval_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        public static string SourceFileRemoval_Recycle {
            get {
                return ResourceManager.GetString("SourceFileRemoval_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After clearing completed items.
        /// </summary>
        public static string SourceFileRemovalTiming_AfterClearingCompletedItems {
            get {
                return ResourceManager.GetString("SourceFileRemovalTiming_AfterClearingCompletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately after the encode completes.
        /// </summary>
        public static string SourceFileRemovalTiming_Immediately {
            get {
                return ResourceManager.GetString("SourceFileRemovalTiming_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string SubtitleBurnInSelection_First {
            get {
                return ResourceManager.GetString("SubtitleBurnInSelection_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign audio track.
        /// </summary>
        public static string SubtitleBurnInSelection_ForeignAudioTrack {
            get {
                return ResourceManager.GetString("SubtitleBurnInSelection_ForeignAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign audio track, else First.
        /// </summary>
        public static string SubtitleBurnInSelection_ForeignAudioTrackElseFirst {
            get {
                return ResourceManager.GetString("SubtitleBurnInSelection_ForeignAudioTrackElseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SubtitleBurnInSelection_None {
            get {
                return ResourceManager.GetString("SubtitleBurnInSelection_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Word.
        /// </summary>
        public static string TitleCapitalizationChoice_EveryWord {
            get {
                return ResourceManager.GetString("TitleCapitalizationChoice_EveryWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First word.
        /// </summary>
        public static string TitleCapitalizationChoice_FirstWord {
            get {
                return ResourceManager.GetString("TitleCapitalizationChoice_FirstWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blu-ray.
        /// </summary>
        public static string TitleType_Bluray {
            get {
                return ResourceManager.GetString("TitleType_Bluray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD.
        /// </summary>
        public static string TitleType_Dvd {
            get {
                return ResourceManager.GetString("TitleType_Dvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string TitleType_Stream {
            get {
                return ResourceManager.GetString("TitleType_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to apply right away.
        /// </summary>
        public static string UpdateMode_PromptApplyImmediately {
            get {
                return ResourceManager.GetString("UpdateMode_PromptApplyImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent (Apply on next launch).
        /// </summary>
        public static string UpdateMode_SilentNextLaunch {
            get {
                return ResourceManager.GetString("UpdateMode_SilentNextLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On exit.
        /// </summary>
        public static string UpdatePromptTiming_OnExit {
            get {
                return ResourceManager.GetString("UpdatePromptTiming_OnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On launch.
        /// </summary>
        public static string UpdatePromptTiming_OnLaunch {
            get {
                return ResourceManager.GetString("UpdatePromptTiming_OnLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string VideoRangeType_Chapters {
            get {
                return ResourceManager.GetString("VideoRangeType_Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        public static string VideoRangeType_Frames {
            get {
                return ResourceManager.GetString("VideoRangeType_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range.
        /// </summary>
        public static string VideoRangeType_Seconds {
            get {
                return ResourceManager.GetString("VideoRangeType_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string WatchedFileStatusLive_Canceled {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string WatchedFileStatusLive_Encoding {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string WatchedFileStatusLive_Failed {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string WatchedFileStatusLive_Output {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string WatchedFileStatusLive_Planned {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string WatchedFileStatusLive_Queued {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string WatchedFileStatusLive_Skipped {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string WatchedFileStatusLive_Succeeded {
            get {
                return ResourceManager.GetString("WatchedFileStatusLive_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System watcher.
        /// </summary>
        public static string WatcherMode_FileSystemWatcher {
            get {
                return ResourceManager.GetString("WatcherMode_FileSystemWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling.
        /// </summary>
        public static string WatcherMode_Polling {
            get {
                return ResourceManager.GetString("WatcherMode_Polling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string WatcherProcessStatus_Disabled {
            get {
                return ResourceManager.GetString("WatcherProcessStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string WatcherProcessStatus_Running {
            get {
                return ResourceManager.GetString("WatcherProcessStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string WatcherProcessStatus_Starting {
            get {
                return ResourceManager.GetString("WatcherProcessStatus_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string WatcherProcessStatus_Stopped {
            get {
                return ResourceManager.GetString("WatcherProcessStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically rename.
        /// </summary>
        public static string WhenFileExists_AutoRename {
            get {
                return ResourceManager.GetString("WhenFileExists_AutoRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string WhenFileExists_Overwrite {
            get {
                return ResourceManager.GetString("WhenFileExists_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string WhenFileExists_Prompt {
            get {
                return ResourceManager.GetString("WhenFileExists_Prompt", resourceCulture);
            }
        }
    }
