//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.EnumsRes", typeof(EnumsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Anamorphic_Custom {
            get {
                return ResourceManager.GetString("Anamorphic_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose.
        /// </summary>
        public static string Anamorphic_Loose {
            get {
                return ResourceManager.GetString("Anamorphic_Loose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Anamorphic_None {
            get {
                return ResourceManager.GetString("Anamorphic_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict.
        /// </summary>
        public static string Anamorphic_Strict {
            get {
                return ResourceManager.GetString("Anamorphic_Strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string Decomb_Bob {
            get {
                return ResourceManager.GetString("Decomb_Bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Decomb_Fast {
            get {
                return ResourceManager.GetString("Decomb_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string Deinterlace_Bob {
            get {
                return ResourceManager.GetString("Deinterlace_Bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Deinterlace_Fast {
            get {
                return ResourceManager.GetString("Deinterlace_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Deinterlace_Slow {
            get {
                return ResourceManager.GetString("Deinterlace_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower.
        /// </summary>
        public static string Deinterlace_Slower {
            get {
                return ResourceManager.GetString("Deinterlace_Slower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hqdn3d.
        /// </summary>
        public static string Denoise_HQDN3D {
            get {
                return ResourceManager.GetString("Denoise_HQDN3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL-Means.
        /// </summary>
        public static string Denoise_NLMeans {
            get {
                return ResourceManager.GetString("Denoise_NLMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string DenoisePreset_Light {
            get {
                return ResourceManager.GetString("DenoisePreset_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DenoisePreset_Medium {
            get {
                return ResourceManager.GetString("DenoisePreset_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string DenoisePreset_Strong {
            get {
                return ResourceManager.GetString("DenoisePreset_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultralight.
        /// </summary>
        public static string DenoisePreset_Ultralight {
            get {
                return ResourceManager.GetString("DenoisePreset_Ultralight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string DenoiseTune_Animation {
            get {
                return ResourceManager.GetString("DenoiseTune_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string DenoiseTune_Film {
            get {
                return ResourceManager.GetString("DenoiseTune_Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        public static string DenoiseTune_Grain {
            get {
                return ResourceManager.GetString("DenoiseTune_Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Motion.
        /// </summary>
        public static string DenoiseTune_HighMotion {
            get {
                return ResourceManager.GetString("DenoiseTune_HighMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string EncodeCompleteActionType_DoNothing {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject {0}:.
        /// </summary>
        public static string EncodeCompleteActionType_EjectDisc {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_EjectDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        public static string EncodeCompleteActionType_Hibernate {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string EncodeCompleteActionType_LogOff {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down.
        /// </summary>
        public static string EncodeCompleteActionType_Shutdown {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string EncodeCompleteActionType_Sleep {
            get {
                return ResourceManager.GetString("EncodeCompleteActionType_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blu-ray.
        /// </summary>
        public static string TitleType_Bluray {
            get {
                return ResourceManager.GetString("TitleType_Bluray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD.
        /// </summary>
        public static string TitleType_Dvd {
            get {
                return ResourceManager.GetString("TitleType_Dvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string TitleType_Stream {
            get {
                return ResourceManager.GetString("TitleType_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string VideoRangeType_Chapters {
            get {
                return ResourceManager.GetString("VideoRangeType_Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        public static string VideoRangeType_Frames {
            get {
                return ResourceManager.GetString("VideoRangeType_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range.
        /// </summary>
        public static string VideoRangeType_Seconds {
            get {
                return ResourceManager.GetString("VideoRangeType_Seconds", resourceCulture);
            }
        }
    }
}
