//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.MainRes", typeof(MainRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VidCoder....
        /// </summary>
        public static string AboutVidCoderMenuItem {
            get {
                return ResourceManager.GetString("AboutVidCoderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added subtitle from file {0}.
        /// </summary>
        public static string AddedSubtitleFromFile {
            get {
                return ResourceManager.GetString("AddedSubtitleFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Multiple Titles to Queue....
        /// </summary>
        public static string AddMultipleTitlesToQueueLabel {
            get {
                return ResourceManager.GetString("AddMultipleTitlesToQueueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string AddToQueueLabel {
            get {
                return ResourceManager.GetString("AddToQueueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track.
        /// </summary>
        public static string AddTrackButton {
            get {
                return ResourceManager.GetString("AddTrackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle:.
        /// </summary>
        public static string AngleLabel {
            get {
                return ResourceManager.GetString("AngleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply current encoding settings.
        /// </summary>
        public static string ApplyCurrentEncodingSettings {
            get {
                return ResourceManager.GetString("ApplyCurrentEncodingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio encoding options.
        /// </summary>
        public static string AudioEncodingOptionsToolTip {
            get {
                return ResourceManager.GetString("AudioEncodingOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the current file and open the disc?.
        /// </summary>
        public static string AutoplayDiscConfirmationMessage {
            get {
                return ResourceManager.GetString("AutoplayDiscConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average FPS:.
        /// </summary>
        public static string AverageFpsLabel {
            get {
                return ResourceManager.GetString("AverageFpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string BitrateColumn {
            get {
                return ResourceManager.GetString("BitrateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBR Auto.
        /// </summary>
        public static string CbrAuto {
            get {
                return ResourceManager.GetString("CbrAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Markers:.
        /// </summary>
        public static string ChapterMarkersLabel {
            get {
                return ResourceManager.GetString("ChapterMarkersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        public static string ChaptersSummary {
            get {
                return ResourceManager.GetString("ChaptersSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a video source:.
        /// </summary>
        public static string ChooseVideoSourceLabel {
            get {
                return ResourceManager.GetString("ChooseVideoSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Completed.
        /// </summary>
        public static string ClearCompleted {
            get {
                return ResourceManager.GetString("ClearCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recent files.
        /// </summary>
        public static string ClearRecentFilesButtonToolTip {
            get {
                return ResourceManager.GetString("ClearRecentFilesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Video Source.
        /// </summary>
        public static string CloseVideoSourceMenuItem {
            get {
                return ResourceManager.GetString("CloseVideoSourceMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close video source.
        /// </summary>
        public static string CloseVideoSourceToolTip {
            get {
                return ResourceManager.GetString("CloseVideoSourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed ({0}).
        /// </summary>
        public static string CompletedWithTotal {
            get {
                return ResourceManager.GetString("CompletedWithTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Log.
        /// </summary>
        public static string CopyLog {
            get {
                return ResourceManager.GetString("CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy log:{0}{0}{1}.
        /// </summary>
        public static string CouldNotCopyLogError {
            get {
                return ResourceManager.GetString("CouldNotCopyLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy text..
        /// </summary>
        public static string CouldNotCopyTextError {
            get {
                return ResourceManager.GetString("CouldNotCopyTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete {0}
        ///
        ///{1}.
        /// </summary>
        public static string CouldNotDeleteFile {
            get {
                return ResourceManager.GetString("CouldNotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load picker: .
        /// </summary>
        public static string CouldNotLoadPickerMessage {
            get {
                return ResourceManager.GetString("CouldNotLoadPickerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load preset: .
        /// </summary>
        public static string CouldNotLoadPresetMessage {
            get {
                return ResourceManager.GetString("CouldNotLoadPresetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save preset &apos;{0}&apos;:{1}{2}.
        /// </summary>
        public static string CouldNotSavePresetMessage {
            get {
                return ResourceManager.GetString("CouldNotSavePresetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save queue:{0}{1}.
        /// </summary>
        public static string CouldNotSaveQueueMessage {
            get {
                return ResourceManager.GetString("CouldNotSaveQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current FPS:.
        /// </summary>
        public static string CurrentFpsLabel {
            get {
                return ResourceManager.GetString("CurrentFpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize columns....
        /// </summary>
        public static string CustomizeColumnsMenuItem {
            get {
                return ResourceManager.GetString("CustomizeColumnsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom video player could not be found at {0}..
        /// </summary>
        public static string CustomVideoPlayerError {
            get {
                return ResourceManager.GetString("CustomVideoPlayerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is too old to upgrade. Run VidCoder {0} once to upgrade it to a compatible version, then try this version again..
        /// </summary>
        public static string DataTooOldRunVidCoderVersion {
            get {
                return ResourceManager.GetString("DataTooOldRunVidCoderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} source file(s)/folder(s)?.
        /// </summary>
        public static string DeleteSourceFilesConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteSourceFilesConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        public static string DeleteSourceFilesConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteSourceFilesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationColumnHeader {
            get {
                return ResourceManager.GetString("DestinationColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        public static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit the encode destination..
        /// </summary>
        public static string DestinationToolTip {
            get {
                return ResourceManager.GetString("DestinationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create output folder. Error details:
        ///
        ///{0}.
        /// </summary>
        public static string DirectoryCreateErrorMessage {
            get {
                return ResourceManager.GetString("DirectoryCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating folder.
        /// </summary>
        public static string DirectoryCreateErrorTitle {
            get {
                return ResourceManager.GetString("DirectoryCreateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load for editing. The disc is no longer in the drive..
        /// </summary>
        public static string DiscNotInDriveError {
            get {
                return ResourceManager.GetString("DiscNotInDriveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Or drag video files or folders here).
        /// </summary>
        public static string DragFilesHereLabel {
            get {
                return ResourceManager.GetString("DragFilesHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit chapters.
        /// </summary>
        public static string EditChaptersButtonAutomationName {
            get {
                return ResourceManager.GetString("EditChaptersButtonAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        public static string ElapsedTimeColumnHeader {
            get {
                return ResourceManager.GetString("ElapsedTimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string Encode {
            get {
                return ResourceManager.GetString("Encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VidCoder has finished all encode jobs in the queue..
        /// </summary>
        public static string EncodeCompleteBalloonMessage {
            get {
                return ResourceManager.GetString("EncodeCompleteBalloonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding completed.
        /// </summary>
        public static string EncodeCompleteBalloonTitle {
            get {
                return ResourceManager.GetString("EncodeCompleteBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode completed..
        /// </summary>
        public static string EncodeCompleted {
            get {
                return ResourceManager.GetString("EncodeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Details.
        /// </summary>
        public static string EncodeDetailsMenuItem {
            get {
                return ResourceManager.GetString("EncodeDetailsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are encodes in progress. Are you sure you want to quit?.
        /// </summary>
        public static string EncodesInProgressExitWarning {
            get {
                return ResourceManager.GetString("EncodesInProgressExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes in progress.
        /// </summary>
        public static string EncodesInProgressExitWarningTitle {
            get {
                return ResourceManager.GetString("EncodesInProgressExitWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        public static string EncodingLabel {
            get {
                return ResourceManager.GetString("EncodingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding settings: {0}.
        /// </summary>
        public static string EncodingSettingsButton {
            get {
                return ResourceManager.GetString("EncodingSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video and audio codecs, sizing, filters, container.
        /// </summary>
        public static string EncodingSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("EncodingSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Settings.
        /// </summary>
        public static string EncodingSettingsMenuItem {
            get {
                return ResourceManager.GetString("EncodingSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End chapter.
        /// </summary>
        public static string EndChapterAutomationName {
            get {
                return ResourceManager.GetString("EndChapterAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Folder of Video Files....
        /// </summary>
        public static string EnqueueFolderOfVideoFiles {
            get {
                return ResourceManager.GetString("EnqueueFolderOfVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Multiple Files....
        /// </summary>
        public static string EnqueueMultipleFiles {
            get {
                return ResourceManager.GetString("EnqueueMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA:.
        /// </summary>
        public static string EtaLabel {
            get {
                return ResourceManager.GetString("EtaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Preset....
        /// </summary>
        public static string ExportPreset {
            get {
                return ResourceManager.GetString("ExportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export preset.
        /// </summary>
        public static string ExportPresetFilePickerText {
            get {
                return ResourceManager.GetString("ExportPresetFilePickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Queue....
        /// </summary>
        public static string ExportQueue {
            get {
                return ResourceManager.GetString("ExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export queue.
        /// </summary>
        public static string ExportQueueFilePickerText {
            get {
                return ResourceManager.GetString("ExportQueueFilePickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FileSizeColumnHeader {
            get {
                return ResourceManager.GetString("FileSizeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Audio Search.
        /// </summary>
        public static string ForeignAudioSearch {
            get {
                return ResourceManager.GetString("ForeignAudioSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global options.
        /// </summary>
        public static string GlobalOptionsLabel {
            get {
                return ResourceManager.GetString("GlobalOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        public static string ImportErrorTitle {
            get {
                return ResourceManager.GetString("ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export.
        /// </summary>
        public static string ImportExportRibbonButton {
            get {
                return ResourceManager.GetString("ImportExportRibbonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Preset....
        /// </summary>
        public static string ImportPreset {
            get {
                return ResourceManager.GetString("ImportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import preset file.
        /// </summary>
        public static string ImportPresetFilePickerTitle {
            get {
                return ResourceManager.GetString("ImportPresetFilePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Queue....
        /// </summary>
        public static string ImportQueue {
            get {
                return ResourceManager.GetString("ImportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import queue file.
        /// </summary>
        public static string ImportQueueFilePickerTitle {
            get {
                return ResourceManager.GetString("ImportQueueFilePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible database file.
        /// </summary>
        public static string IncompatibleDatabaseFileTitle {
            get {
                return ResourceManager.GetString("IncompatibleDatabaseFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error launching URL: {0}.
        /// </summary>
        public static string LaunchUrlError {
            get {
                return ResourceManager.GetString("LaunchUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string LengthPreviewLabel {
            get {
                return ResourceManager.GetString("LengthPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogMenuItem {
            get {
                return ResourceManager.GetString("LogMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Modified).
        /// </summary>
        public static string ModifiedAffix {
            get {
                return ResourceManager.GetString("ModifiedAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Bottom.
        /// </summary>
        public static string MoveToBottomMenuItem {
            get {
                return ResourceManager.GetString("MoveToBottomMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Top.
        /// </summary>
        public static string MoveToTopMenuItem {
            get {
                return ResourceManager.GetString("MoveToTopMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} has finished downloading..
        /// </summary>
        public static string NewVersionDownloadFinishedOnLaunchStatus {
            get {
                return ResourceManager.GetString("NewVersionDownloadFinishedOnLaunchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} has finished downloading and will install on exit..
        /// </summary>
        public static string NewVersionDownloadFinishedStatus {
            get {
                return ResourceManager.GetString("NewVersionDownloadFinishedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available. Update download has started..
        /// </summary>
        public static string NewVersionDownloadStartedStatus {
            get {
                return ResourceManager.GetString("NewVersionDownloadStartedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio found on source..
        /// </summary>
        public static string NoAudioDescription {
            get {
                return ResourceManager.GetString("NoAudioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio.
        /// </summary>
        public static string NoAudioSummary {
            get {
                return ResourceManager.GetString("NoAudioSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string NoneParen {
            get {
                return ResourceManager.GetString("NoneParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subtitles.
        /// </summary>
        public static string NoSubtitlesSummary {
            get {
                return ResourceManager.GetString("NoSubtitlesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Data Folder.
        /// </summary>
        public static string OpenAppDataFolder {
            get {
                return ResourceManager.GetString("OpenAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        public static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DVD/Blu-ray Folder....
        /// </summary>
        public static string OpenDiscFolder {
            get {
                return ResourceManager.GetString("OpenDiscFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0}.
        /// </summary>
        public static string OpenFormat {
            get {
                return ResourceManager.GetString("OpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening folder....
        /// </summary>
        public static string OpeningFolderStatus {
            get {
                return ResourceManager.GetString("OpeningFolderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log.
        /// </summary>
        public static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source folder.
        /// </summary>
        public static string OpenSourceFolderOption {
            get {
                return ResourceManager.GetString("OpenSourceFolderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenSourceLabel {
            get {
                return ResourceManager.GetString("OpenSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source.
        /// </summary>
        public static string OpenSourceRibbonButton {
            get {
                return ResourceManager.GetString("OpenSourceRibbonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Video File....
        /// </summary>
        public static string OpenVideoFile {
            get {
                return ResourceManager.GetString("OpenVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the output folder for encoded video files..
        /// </summary>
        public static string OutputDirectoryPickerText {
            get {
                return ResourceManager.GetString("OutputDirectoryPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add encode jobs without a default output folder. Press OK to pick one..
        /// </summary>
        public static string OutputFolderRequiredMessage {
            get {
                return ResourceManager.GetString("OutputFolderRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Output Folder Required.
        /// </summary>
        public static string OutputFolderRequiredTitle {
            get {
                return ResourceManager.GetString("OutputFolderRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path is not valid..
        /// </summary>
        public static string OutputPathNotValidMessage {
            get {
                return ResourceManager.GetString("OutputPathNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not valid.
        /// </summary>
        public static string OutputPathNotValidTitle {
            get {
                return ResourceManager.GetString("OutputPathNotValidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a DVD or Blu-ray folder..
        /// </summary>
        public static string PickDiscFolderHelpText {
            get {
                return ResourceManager.GetString("PickDiscFolderHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        public static string PickerMenuItem {
            get {
                return ResourceManager.GetString("PickerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker {0}.
        /// </summary>
        public static string PickerNameTemplate {
            get {
                return ResourceManager.GetString("PickerNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing video....
        /// </summary>
        public static string PlayingVideoMessage {
            get {
                return ResourceManager.GetString("PlayingVideoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing video....
        /// </summary>
        public static string PlayingVideoStatus {
            get {
                return ResourceManager.GetString("PlayingVideoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to discard these changes by switching to another preset?.
        /// </summary>
        public static string PresetDiscardConfirmMessage {
            get {
                return ResourceManager.GetString("PresetDiscardConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes?.
        /// </summary>
        public static string PresetDiscardConfirmTitle {
            get {
                return ResourceManager.GetString("PresetDiscardConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported preset to {0}.
        /// </summary>
        public static string PresetExportSuccessMessage {
            get {
                return ResourceManager.GetString("PresetExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import preset. Check log for details..
        /// </summary>
        public static string PresetImportErrorMessage {
            get {
                return ResourceManager.GetString("PresetImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported preset {0}.
        /// </summary>
        public static string PresetImportSuccessMessage {
            get {
                return ResourceManager.GetString("PresetImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset:.
        /// </summary>
        public static string PresetLabel {
            get {
                return ResourceManager.GetString("PresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored from Completed.
        /// </summary>
        public static string PresetNameRestoredFromCompleted {
            get {
                return ResourceManager.GetString("PresetNameRestoredFromCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored from Queue.
        /// </summary>
        public static string PresetNameRestoredFromQueue {
            get {
                return ResourceManager.GetString("PresetNameRestoredFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewMenuItem {
            get {
                return ResourceManager.GetString("PreviewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string Queued {
            get {
                return ResourceManager.GetString("Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued ({0}).
        /// </summary>
        public static string QueuedWithTotal {
            get {
                return ResourceManager.GetString("QueuedWithTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported queue to {0}.
        /// </summary>
        public static string QueueExportSuccessMessage {
            get {
                return ResourceManager.GetString("QueueExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch {0}.
        /// </summary>
        public static string QueueFormat_Chapters {
            get {
                return ResourceManager.GetString("QueueFormat_Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr {0}-{1}.
        /// </summary>
        public static string QueueFormat_Frames {
            get {
                return ResourceManager.GetString("QueueFormat_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import queue. Check log for details..
        /// </summary>
        public static string QueueImportErrorMessage {
            get {
                return ResourceManager.GetString("QueueImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported queue..
        /// </summary>
        public static string QueueImportSuccessMessage {
            get {
                return ResourceManager.GetString("QueueImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors scanning some files and they were not added to the queue:
        ///
        ///{0}.
        /// </summary>
        public static string QueueMultipleScanErrorMessage {
            get {
                return ResourceManager.GetString("QueueMultipleScanErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error scanning video file(s).
        /// </summary>
        public static string QueueMultipleScanErrorTitle {
            get {
                return ResourceManager.GetString("QueueMultipleScanErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string QueueRangeAll {
            get {
                return ResourceManager.GetString("QueueRangeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click to set the start time and right-click to set the end time..
        /// </summary>
        public static string RangeBarToolTip {
            get {
                return ResourceManager.GetString("RangeBarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove audio track.
        /// </summary>
        public static string RemoveAudioTrackToolTip {
            get {
                return ResourceManager.GetString("RemoveAudioTrackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this?.
        /// </summary>
        public static string RemoveConfirmMessage {
            get {
                return ResourceManager.GetString("RemoveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveConfirmTitle {
            get {
                return ResourceManager.GetString("RemoveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from queue.
        /// </summary>
        public static string RemoveFromQueueToolTip {
            get {
                return ResourceManager.GetString("RemoveFromQueueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read version {0} database file. The highest version recognized by VidCoder {1} is {2}.
        /// </summary>
        public static string RenameDatabaseFileLine1 {
            get {
                return ResourceManager.GetString("RenameDatabaseFileLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to rename the existing file and start with a new one?.
        /// </summary>
        public static string RenameDatabaseFileLine2 {
            get {
                return ResourceManager.GetString("RenameDatabaseFileLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        public static string ReportABugMenuItem {
            get {
                return ResourceManager.GetString("ReportABugMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry all failed jobs.
        /// </summary>
        public static string RetryFailedItemsMenuItem {
            get {
                return ResourceManager.GetString("RetryFailedItemsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revert all unsaved changes?.
        /// </summary>
        public static string RevertConfirmMessage {
            get {
                return ResourceManager.GetString("RevertConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string RevertConfirmTitle {
            get {
                return ResourceManager.GetString("RevertConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string RibbonEncodingGroupLabel {
            get {
                return ResourceManager.GetString("RibbonEncodingGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string RibbonSettingsGroupLabel {
            get {
                return ResourceManager.GetString("RibbonSettingsGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Rate.
        /// </summary>
        public static string SampleRateColumn {
            get {
                return ResourceManager.GetString("SampleRateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to your current picker?.
        /// </summary>
        public static string SaveChangesPickerMessage {
            get {
                return ResourceManager.GetString("SaveChangesPickerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current picker?.
        /// </summary>
        public static string SaveChangesPickerTitle {
            get {
                return ResourceManager.GetString("SaveChangesPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to your current preset?.
        /// </summary>
        public static string SaveChangesPresetMessage {
            get {
                return ResourceManager.GetString("SaveChangesPresetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current preset?.
        /// </summary>
        public static string SaveChangesPresetTitle {
            get {
                return ResourceManager.GetString("SaveChangesPresetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while scanning..
        /// </summary>
        public static string ScanErrorLabel {
            get {
                return ResourceManager.GetString("ScanErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}....
        /// </summary>
        public static string ScanningSourceLabelFormat {
            get {
                return ResourceManager.GetString("ScanningSourceLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output path....
        /// </summary>
        public static string SelectOutputPathButton {
            get {
                return ResourceManager.GetString("SelectOutputPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} other titles have a duration close to this one..
        /// </summary>
        public static string SimilarTitlesToolTip {
            get {
                return ResourceManager.GetString("SimilarTitlesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The sizing interface has been overhauled for 2.0, so your presets may have changed. You may want to inspect them and ensure that they are still set up correctly..
        /// </summary>
        public static string SizingPresetUpgradeWarning {
            get {
                return ResourceManager.GetString("SizingPresetUpgradeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string SourceLabel {
            get {
                return ResourceManager.GetString("SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD/Blu-ray Folder....
        /// </summary>
        public static string SourceOption_DiscFolder {
            get {
                return ResourceManager.GetString("SourceOption_DiscFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File....
        /// </summary>
        public static string SourceOption_VideoFile {
            get {
                return ResourceManager.GetString("SourceOption_VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chapter.
        /// </summary>
        public static string StartChapterAutomationName {
            get {
                return ResourceManager.GetString("StartChapterAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started encoding..
        /// </summary>
        public static string StartedEncoding {
            get {
                return ResourceManager.GetString("StartedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusColumnHeader {
            get {
                return ResourceManager.GetString("StatusColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the encode?.
        /// </summary>
        public static string StopEncodeConfirmationMessage {
            get {
                return ResourceManager.GetString("StopEncodeConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop encode?.
        /// </summary>
        public static string StopEncodeConfirmationTitle {
            get {
                return ResourceManager.GetString("StopEncodeConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped encoding..
        /// </summary>
        public static string StoppedEncoding {
            get {
                return ResourceManager.GetString("StoppedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tracks.
        /// </summary>
        public static string TracksSummaryMultiple {
            get {
                return ResourceManager.GetString("TracksSummaryMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was not applied. If you did not cancel it, try installing it manually..
        /// </summary>
        public static string UpdateNotAppliedError {
            get {
                return ResourceManager.GetString("UpdateNotAppliedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates....
        /// </summary>
        public static string UpdatesMenuItem {
            get {
                return ResourceManager.GetString("UpdatesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a backed up version {0} file. Would you like to use it?.
        /// </summary>
        public static string UseBackupDatabaseLine {
            get {
                return ResourceManager.GetString("UseBackupDatabaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was corrupted and could not be loaded. Some of your settings may have been reset..
        /// </summary>
        public static string UserConfigCorrupted {
            get {
                return ResourceManager.GetString("UserConfigCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VidCoder Homepage.
        /// </summary>
        public static string VidCoderHomepageMenuItem {
            get {
                return ResourceManager.GetString("VidCoderHomepageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video encoding options.
        /// </summary>
        public static string VideoEncodingOptionsToolTip {
            get {
                return ResourceManager.GetString("VideoEncodingOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error playing video..
        /// </summary>
        public static string VideoPlayError {
            get {
                return ResourceManager.GetString("VideoPlayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When done.
        /// </summary>
        public static string WhenDoneLabel {
            get {
                return ResourceManager.GetString("WhenDoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowsMenu {
            get {
                return ResourceManager.GetString("WindowsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with current job(s): {0}.
        /// </summary>
        public static string WithCurrentJobsFormat {
            get {
                return ResourceManager.GetString("WithCurrentJobsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with queue: {0}.
        /// </summary>
        public static string WithQueueFormat {
            get {
                return ResourceManager.GetString("WithQueueFormat", resourceCulture);
            }
        }
    }
}
