//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.OptionsRes", typeof(OptionsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string AddEllipsesButton {
            get {
                return ResourceManager.GetString("AddEllipsesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string AdvancedOptionsSection {
            get {
                return ResourceManager.GetString("AdvancedOptionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedTab {
            get {
                return ResourceManager.GetString("AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic updates.
        /// </summary>
        public static string AutomaticUpdatesCheckBox {
            get {
                return ResourceManager.GetString("AutomaticUpdatesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause encoding when any of these processes are running:.
        /// </summary>
        public static string AutoPauseLabel {
            get {
                return ResourceManager.GetString("AutoPauseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause when battery is low.
        /// </summary>
        public static string AutoPauseLowBatteryCheckbox {
            get {
                return ResourceManager.GetString("AutoPauseLowBatteryCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause when disk space falls below:.
        /// </summary>
        public static string AutoPauseLowDiskSpaceCheckbox {
            get {
                return ResourceManager.GetString("AutoPauseLowDiskSpaceCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic pausing.
        /// </summary>
        public static string AutoPauseSectionLabel {
            get {
                return ResourceManager.GetString("AutoPauseSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string BetaSection {
            get {
                return ResourceManager.GetString("BetaSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re running the Beta version. This can run side-by-side with the stable version..
        /// </summary>
        public static string BetaUpdatesInBeta {
            get {
                return ResourceManager.GetString("BetaUpdatesInBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Beta track to get more frequent updates.
        /// </summary>
        public static string BetaUpdatesNonBeta {
            get {
                return ResourceManager.GetString("BetaUpdatesNonBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beware: this version is more likely to have bugs and crashes..
        /// </summary>
        public static string BetaUpdatesNonBetaWarning {
            get {
                return ResourceManager.GetString("BetaUpdatesNonBetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string CheckNowButton {
            get {
                return ResourceManager.GetString("CheckNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the default output folder for encoded video files..
        /// </summary>
        public static string ChooseDefaultOutputFolder {
            get {
                return ResourceManager.GetString("ChooseDefaultOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the .wav file you want to use for the completion sound..
        /// </summary>
        public static string CompletionWavFilePickTitle {
            get {
                return ResourceManager.GetString("CompletionWavFilePickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the encode log to a custom folder.
        /// </summary>
        public static string CopyLogToCustomFolderLabel {
            get {
                return ResourceManager.GetString("CopyLogToCustomFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the encode log to the same folder as the encoded video.
        /// </summary>
        public static string CopyLogToOutputFolderLabel {
            get {
                return ResourceManager.GetString("CopyLogToOutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU throttling - Allowed Cores:.
        /// </summary>
        public static string CpuThrottlingLabel {
            get {
                return ResourceManager.GetString("CpuThrottlingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CPU throttling to limit the number of processor cores VidCoder can use when encoding..
        /// </summary>
        public static string CpuThrottlingToolTip {
            get {
                return ResourceManager.GetString("CpuThrottlingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: {0}.
        /// </summary>
        public static string CurrentVersionLabel {
            get {
                return ResourceManager.GetString("CurrentVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom player:.
        /// </summary>
        public static string CustomPlayerLabel {
            get {
                return ResourceManager.GetString("CustomPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom folder for previews:.
        /// </summary>
        public static string CustomPreviewFolderCheckBox {
            get {
                return ResourceManager.GetString("CustomPreviewFolderCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the video player you wish to use for files..
        /// </summary>
        public static string CustomVideoPlayerToolTip {
            get {
                return ResourceManager.GetString("CustomVideoPlayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete source files after clearing successful completed items.
        /// </summary>
        public static string DeleteSourceAfterCompletionCheckBox {
            get {
                return ResourceManager.GetString("DeleteSourceAfterCompletionCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding latest version....
        /// </summary>
        public static string DownloadingInfoStatus {
            get {
                return ResourceManager.GetString("DownloadingInfoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update {0}:.
        /// </summary>
        public static string DownloadingStatus {
            get {
                return ResourceManager.GetString("DownloadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop scan order:.
        /// </summary>
        public static string DragDropScanOrderLabel {
            get {
                return ResourceManager.GetString("DragDropScanOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD reading.
        /// </summary>
        public static string DvdReadingSection {
            get {
                return ResourceManager.GetString("DvdReadingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable LibDVDNav (Change requires program restart. Required to support multiple angles).
        /// </summary>
        public static string EnableLibDvdNavCheckBox {
            get {
                return ResourceManager.GetString("EnableLibDvdNavCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of encode retries:.
        /// </summary>
        public static string EncodeRetriesLabel {
            get {
                return ResourceManager.GetString("EncodeRetriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding batch of files:.
        /// </summary>
        public static string EncodingBatchOfFiles {
            get {
                return ResourceManager.GetString("EncodingBatchOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding single file:.
        /// </summary>
        public static string EncodingSingleFile {
            get {
                return ResourceManager.GetString("EncodingSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available options: {0}.
        /// </summary>
        public static string FileNameFormatOptions {
            get {
                return ResourceManager.GetString("FileNameFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSection {
            get {
                return ResourceManager.GetString("GeneralSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language:.
        /// </summary>
        public static string InterfaceLanguageLabel {
            get {
                return ResourceManager.GetString("InterfaceLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep files from failed or stopped encodes.
        /// </summary>
        public static string KeepFailedFilesCheckBox {
            get {
                return ResourceManager.GetString("KeepFailedFilesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string LoggingSection {
            get {
                return ResourceManager.GetString("LoggingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Verbosity:.
        /// </summary>
        public static string LoggingVerbosityLabel {
            get {
                return ResourceManager.GetString("LoggingVerbosityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low disk space threshold in gigabytes.
        /// </summary>
        public static string LowDiskSpaceThresholdAutomationName {
            get {
                return ResourceManager.GetString("LowDiskSpaceThresholdAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum simultaneous encoding jobs:.
        /// </summary>
        public static string MaxSimultaneousEncodesLabel {
            get {
                return ResourceManager.GetString("MaxSimultaneousEncodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how many simultaneous encode jobs are allowed. Useful for machines with many CPU cores..
        /// </summary>
        public static string MaxSimultaneousEncodesToolTip {
            get {
                return ResourceManager.GetString("MaxSimultaneousEncodesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray.
        /// </summary>
        public static string MinimizeToSystemTrayRadioButton {
            get {
                return ResourceManager.GetString("MinimizeToSystemTrayRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to task bar.
        /// </summary>
        public static string MinimizeToTaskBarRadioButton {
            get {
                return ResourceManager.GetString("MinimizeToTaskBarRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of title to scan (seconds):.
        /// </summary>
        public static string MinScanLengthLabel {
            get {
                return ResourceManager.GetString("MinScanLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new language will take effect after you exit and restart VidCoder..
        /// </summary>
        public static string NewLanguageRestartDialogMessage {
            get {
                return ResourceManager.GetString("NewLanguageRestartDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string OpenLogFolderButton {
            get {
                return ResourceManager.GetString("OpenLogFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsDialogTitle {
            get {
                return ResourceManager.GetString("OptionsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder.
        /// </summary>
        public static string OutputFolderSection {
            get {
                return ResourceManager.GetString("OutputFolderSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayersSection {
            get {
                return ResourceManager.GetString("PlayersSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound on queue completion.
        /// </summary>
        public static string PlaySoundOnQueueCompletionCheckBox {
            get {
                return ResourceManager.GetString("PlaySoundOnQueueCompletionCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred DVD player:.
        /// </summary>
        public static string PreferredDvdPlayerLabel {
            get {
                return ResourceManager.GetString("PreferredDvdPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the player you want to use for DVD sources..
        /// </summary>
        public static string PreferredDvdPlayerToolTip {
            get {
                return ResourceManager.GetString("PreferredDvdPlayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Created and Modified time when converting files.
        /// </summary>
        public static string PreserveModifyTimeFilesCheckBox {
            get {
                return ResourceManager.GetString("PreserveModifyTimeFilesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of picture previews to scan:.
        /// </summary>
        public static string PreviewCountLabel {
            get {
                return ResourceManager.GetString("PreviewCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Normal.
        /// </summary>
        public static string Priority_AboveNormal {
            get {
                return ResourceManager.GetString("Priority_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Normal.
        /// </summary>
        public static string Priority_BelowNormal {
            get {
                return ResourceManager.GetString("Priority_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Priority_High {
            get {
                return ResourceManager.GetString("Priority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Priority_Idle {
            get {
                return ResourceManager.GetString("Priority_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Priority_Normal {
            get {
                return ResourceManager.GetString("Priority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process options.
        /// </summary>
        public static string ProcessOptionsLabel {
            get {
                return ResourceManager.GetString("ProcessOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessTab {
            get {
                return ResourceManager.GetString("ProcessTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt for updates:.
        /// </summary>
        public static string PromptForUpdatesLabel {
            get {
                return ResourceManager.GetString("PromptForUpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized Extensions:.
        /// </summary>
        public static string RecognizedExtensionsLabel {
            get {
                return ResourceManager.GetString("RecognizedExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When scanning folders for video files, add files with these extensions. (Comma separated).
        /// </summary>
        public static string RecognizedExtensionsToolTip {
            get {
                return ResourceManager.GetString("RecognizedExtensionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember previously used files and folders.
        /// </summary>
        public static string RememberPreviousFilesCheckBox {
            get {
                return ResourceManager.GetString("RememberPreviousFilesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically resume encoding on restart.
        /// </summary>
        public static string ResumeEncodingOnRestartCheckBox {
            get {
                return ResourceManager.GetString("ResumeEncodingOnRestartCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        public static string ScanningSection {
            get {
                return ResourceManager.GetString("ScanningSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SoundSection {
            get {
                return ResourceManager.GetString("SoundSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System tray.
        /// </summary>
        public static string SystemTraySection {
            get {
                return ResourceManager.GetString("SystemTraySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger &quot;When done&quot; action when there are failed encode jobs.
        /// </summary>
        public static string TriggerWhenDoneWithFailedJobsCheckBox {
            get {
                return ResourceManager.GetString("TriggerWhenDoneWithFailedJobsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed..
        /// </summary>
        public static string UpdateFailedStatus {
            get {
                return ResourceManager.GetString("UpdateFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} ready. It will install when you exit the program..
        /// </summary>
        public static string UpdateReadyStatus {
            get {
                return ResourceManager.GetString("UpdateReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesSection {
            get {
                return ResourceManager.GetString("UpdatesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesTab {
            get {
                return ResourceManager.GetString("UpdatesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string UpdateStatusSection {
            get {
                return ResourceManager.GetString("UpdateStatusSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VidCoder is up to date..
        /// </summary>
        public static string UpToDateStatus {
            get {
                return ResourceManager.GetString("UpToDateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in player for previews.
        /// </summary>
        public static string UseBuiltInPlayerForPreviewsCheckBox {
            get {
                return ResourceManager.GetString("UseBuiltInPlayerForPreviewsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom .wav file:.
        /// </summary>
        public static string UseCustomWavLabel {
            get {
                return ResourceManager.GetString("UseCustomWavLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use OS Language.
        /// </summary>
        public static string UseOSLanguage {
            get {
                return ResourceManager.GetString("UseOSLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system player.
        /// </summary>
        public static string UseSystemPlayer {
            get {
                return ResourceManager.GetString("UseSystemPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use worker process to encode.
        /// </summary>
        public static string UseWorkerProcessCheckBox {
            get {
                return ResourceManager.GetString("UseWorkerProcessCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Files:.
        /// </summary>
        public static string VideoFilesLabel {
            get {
                return ResourceManager.GetString("VideoFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the player to use for video files..
        /// </summary>
        public static string VideoPlayerFilePickTitle {
            get {
                return ResourceManager.GetString("VideoPlayerFilePickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a file already exists....
        /// </summary>
        public static string WhenFileAlreadyExists {
            get {
                return ResourceManager.GetString("WhenFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker process priority:.
        /// </summary>
        public static string WorkerProcessPriorityLabel {
            get {
                return ResourceManager.GetString("WorkerProcessPriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worker process option will take effect after you exit and restart VidCoder..
        /// </summary>
        public static string WorkerProcessRestartDialogMessage {
            get {
                return ResourceManager.GetString("WorkerProcessRestartDialogMessage", resourceCulture);
            }
        }
    }
}
