//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.PickerRes", typeof(PickerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio track name.
        /// </summary>
        public static string AddAudioTrackNameButton {
            get {
                return ResourceManager.GetString("AddAudioTrackNameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language.
        /// </summary>
        public static string AddLanguageButton {
            get {
                return ResourceManager.GetString("AddLanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subtitle track name.
        /// </summary>
        public static string AddSubtitleTrackNameButton {
            get {
                return ResourceManager.GetString("AddSubtitleTrackNameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks for these languages.
        /// </summary>
        public static string AllTracksForTheseLanguagesRadioButton {
            get {
                return ResourceManager.GetString("AllTracksForTheseLanguagesRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks for this language.
        /// </summary>
        public static string AllTracksForThisLanguageRadioButton {
            get {
                return ResourceManager.GetString("AllTracksForThisLanguageRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last selected - Picks the last selected audio track if a match is found, otherwise picks the first.
        ///First - Include only the first audio track.
        ///By index - Pick by track index (1-based)
        ///Language(s) - Pick by language
        ///All - Include all audio tracks..
        /// </summary>
        public static string AudioSelectionModeToolTip {
            get {
                return ResourceManager.GetString("AudioSelectionModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start encoding after scan.
        /// </summary>
        public static string AutoEncodeOnScanCheckBox {
            get {
                return ResourceManager.GetString("AutoEncodeOnScanCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically queue after scanning.
        /// </summary>
        public static string AutoQueueOnScanCheckBox {
            get {
                return ResourceManager.GetString("AutoQueueOnScanCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn in.
        /// </summary>
        public static string BurnInCheckBox {
            get {
                return ResourceManager.GetString("BurnInCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn in:.
        /// </summary>
        public static string BurnInLabel {
            get {
                return ResourceManager.GetString("BurnInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By index.
        /// </summary>
        public static string ByIndexRadioButton {
            get {
                return ResourceManager.GetString("ByIndexRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change capitalization to.
        /// </summary>
        public static string ChangeCaptializationLabel {
            get {
                return ResourceManager.GetString("ChangeCaptializationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change word separator to.
        /// </summary>
        public static string ChangeWordSeparatorLabel {
            get {
                return ResourceManager.GetString("ChangeWordSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter range end.
        /// </summary>
        public static string ChapterRangeEndAutomationName {
            get {
                return ResourceManager.GetString("ChapterRangeEndAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter range start.
        /// </summary>
        public static string ChapterRangeStartAutomationName {
            get {
                return ResourceManager.GetString("ChapterRangeStartAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom {0}.
        /// </summary>
        public static string CustomPickerNameTemplate {
            get {
                return ResourceManager.GetString("CustomPickerNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom track names.
        /// </summary>
        public static string CustomTrackNamesCheckBox {
            get {
                return ResourceManager.GetString("CustomTrackNamesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultCheckBox {
            get {
                return ResourceManager.GetString("DefaultCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationSection {
            get {
                return ResourceManager.GetString("DestinationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter titles by duration.
        /// </summary>
        public static string DurationFilterCheckBoxAutomationName {
            get {
                return ResourceManager.GetString("DurationFilterCheckBoxAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration filter end minutes.
        /// </summary>
        public static string DurationFilterEndAutomationName {
            get {
                return ResourceManager.GetString("DurationFilterEndAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration filter start minutes.
        /// </summary>
        public static string DurationFilterStartAutomationName {
            get {
                return ResourceManager.GetString("DurationFilterStartAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string EncodingSection {
            get {
                return ResourceManager.GetString("EncodingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add external subtitle files ({0}) with same name as input video file.
        /// </summary>
        public static string ExternalSubtitleImportCheckBox {
            get {
                return ResourceManager.GetString("ExternalSubtitleImportCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also recognizes fileName.lng.ext, where lng is the ISO language name and ext is the subtitle file extension..
        /// </summary>
        public static string ExternalSubtitleImportToolTip {
            get {
                return ResourceManager.GetString("ExternalSubtitleImportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback language:.
        /// </summary>
        public static string FallbackLanguageLabel {
            get {
                return ResourceManager.GetString("FallbackLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the language is not identified in the subtitle file name, like myVideo.srt, assume it is this language..
        /// </summary>
        public static string FallbackLanguageToolTip {
            get {
                return ResourceManager.GetString("FallbackLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark first as default.
        /// </summary>
        public static string FirstAsDefaultCheckBox {
            get {
                return ResourceManager.GetString("FirstAsDefaultCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First track of each language.
        /// </summary>
        public static string FirstTrackOfEachLanguageRadioButton {
            get {
                return ResourceManager.GetString("FirstTrackOfEachLanguageRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First track.
        /// </summary>
        public static string FirstTrackRadioButton {
            get {
                return ResourceManager.GetString("FirstTrackRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced only.
        /// </summary>
        public static string ForcedOnlyCheckBox {
            get {
                return ResourceManager.GetString("ForcedOnlyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick only titles with height.
        /// </summary>
        public static string HeightFilterCheckBox {
            get {
                return ResourceManager.GetString("HeightFilterCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter titles by height.
        /// </summary>
        public static string HeightFilterCheckBoxAutomationName {
            get {
                return ResourceManager.GetString("HeightFilterCheckBoxAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height filter value.
        /// </summary>
        public static string HeightFilterValueAutomationName {
            get {
                return ResourceManager.GetString("HeightFilterValueAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore files below.
        /// </summary>
        public static string IgnoreFilesBelowCheckBox {
            get {
                return ResourceManager.GetString("IgnoreFilesBelowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language(s).
        /// </summary>
        public static string LanguagesRadioButton {
            get {
                return ResourceManager.GetString("LanguagesRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last selected.
        /// </summary>
        public static string LastSelectedRadioButton {
            get {
                return ResourceManager.GetString("LastSelectedRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string MetadataSection {
            get {
                return ResourceManager.GetString("MetadataSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark the first subtitle track as default, so it shows up automatically when playing the video..
        /// </summary>
        public static string MultipleSubtitleDefaultToolTip {
            get {
                return ResourceManager.GetString("MultipleSubtitleDefaultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only change capitalization if all lowercase or all uppercase.
        /// </summary>
        public static string OnlyChangeCapitalizationIfAllSameLabel {
            get {
                return ResourceManager.GetString("OnlyChangeCapitalizationIfAllSameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if different language from audio.
        /// </summary>
        public static string OnlyIfDifferentFromAudioCheckBox {
            get {
                return ResourceManager.GetString("OnlyIfDifferentFromAudioCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name format.
        /// </summary>
        public static string OutputFileNameFormatAutomationName {
            get {
                return ResourceManager.GetString("OutputFileNameFormatAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder:.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output location.
        /// </summary>
        public static string OutputLocation {
            get {
                return ResourceManager.GetString("OutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override folder:.
        /// </summary>
        public static string OverrideDirectoryCheckBox {
            get {
                return ResourceManager.GetString("OverrideDirectoryCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available options: {0}.
        /// </summary>
        public static string OverrideNameFormatLabel {
            get {
                return ResourceManager.GetString("OverrideNameFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass through video metadata (director, release date, actors, etc).
        /// </summary>
        public static string PassThroughMetadataCheckBox {
            get {
                return ResourceManager.GetString("PassThroughMetadataCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string PickerAudioSectionName {
            get {
                return ResourceManager.GetString("PickerAudioSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker: {0}.
        /// </summary>
        public static string PickerButtonFormat {
            get {
                return ResourceManager.GetString("PickerButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;Foreign audio scan&apos; track.
        /// </summary>
        public static string PickerForeignAudioCheckBox {
            get {
                return ResourceManager.GetString("PickerForeignAudioCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically pick titles, audio, subtitles and destination.
        /// </summary>
        public static string PickerHelpText {
            get {
                return ResourceManager.GetString("PickerHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        public static string PickerSubtitleSectionName {
            get {
                return ResourceManager.GetString("PickerSubtitleSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        public static string PostEncodeArgumentsLabel {
            get {
                return ResourceManager.GetString("PostEncodeArgumentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments to pass to the program. Use {file} for the file output path, {folder} for containing folder path, {sourcepath} for the full source path, or other path options like {title} and {date} (see Naming Format)..
        /// </summary>
        public static string PostEncodeArgumentsToolTip {
            get {
                return ResourceManager.GetString("PostEncodeArgumentsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-encoding.
        /// </summary>
        public static string PostEncodingSection {
            get {
                return ResourceManager.GetString("PostEncodingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker has specified the encoding preset..
        /// </summary>
        public static string PresetDisabledForPickerToolTip {
            get {
                return ResourceManager.GetString("PresetDisabledForPickerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use preset:.
        /// </summary>
        public static string PresetLabel {
            get {
                return ResourceManager.GetString("PresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will override any preset picked in the main window..
        /// </summary>
        public static string PresetOverrideToolTip {
            get {
                return ResourceManager.GetString("PresetOverrideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this language..
        /// </summary>
        public static string RemoveLanguageToolTip {
            get {
                return ResourceManager.GetString("RemoveLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated - ex. 2,5.
        /// </summary>
        public static string SelectTracksHelpText {
            get {
                return ResourceManager.GetString("SelectTracksHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tracks:.
        /// </summary>
        public static string SelectTracksLabel {
            get {
                return ResourceManager.GetString("SelectTracksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send file to:.
        /// </summary>
        public static string SendFileToLabel {
            get {
                return ResourceManager.GetString("SendFileToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark the subtitle track as default, so it will show up automatically when playing the video..
        /// </summary>
        public static string SingleSubtitleDefaultToolTip {
            get {
                return ResourceManager.GetString("SingleSubtitleDefaultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort language(s) to top:.
        /// </summary>
        public static string SortLanguagesLabel {
            get {
                return ResourceManager.GetString("SortLanguagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        public static string SourceCleanupPreviewLabel {
            get {
                return ResourceManager.GetString("SourceCleanupPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm before removing.
        /// </summary>
        public static string SourceFileRemovalConfirmationCheckBox {
            get {
                return ResourceManager.GetString("SourceFileRemovalConfirmationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file removal after successful encode:.
        /// </summary>
        public static string SourceFileRemovalLabel {
            get {
                return ResourceManager.GetString("SourceFileRemovalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source name cleanup.
        /// </summary>
        public static string SourceNameCleanupSection {
            get {
                return ResourceManager.GetString("SourceNameCleanupSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign audio scan.
        /// </summary>
        public static string SubtitleSelectionMode_ForeignAudioSearch {
            get {
                return ResourceManager.GetString("SubtitleSelectionMode_ForeignAudioSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last selected - Picks the last selected subtitle track if a match is found, otherwise pick no tracks.
        ///None - No subtitles are included.
        ///First - Include only the first subtitle.
        ///By index - Pick by track index (1-based)
        ///Language(s) - Pick by language
        ///All - Include all subtitles..
        /// </summary>
        public static string SubtitleSelectionModeToolTip {
            get {
                return ResourceManager.GetString("SubtitleSelectionModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range end.
        /// </summary>
        public static string TimeRangeEndAutomationName {
            get {
                return ResourceManager.GetString("TimeRangeEndAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range:.
        /// </summary>
        public static string TimeRangeLabel {
            get {
                return ResourceManager.GetString("TimeRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range start.
        /// </summary>
        public static string TimeRangeStartAutomationName {
            get {
                return ResourceManager.GetString("TimeRangeStartAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0}.
        /// </summary>
        public static string TrackAutomationFormat {
            get {
                return ResourceManager.GetString("TrackAutomationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track selection:.
        /// </summary>
        public static string TrackSelectionLabel {
            get {
                return ResourceManager.GetString("TrackSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom file naming format:.
        /// </summary>
        public static string UseCustomFileNameFormatCheckBox {
            get {
                return ResourceManager.GetString("UseCustomFileNameFormatCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global setting.
        /// </summary>
        public static string UseGlobalSettingToolTip {
            get {
                return ResourceManager.GetString("UseGlobalSettingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video selection.
        /// </summary>
        public static string VideoSelectionSection {
            get {
                return ResourceManager.GetString("VideoSelectionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When file already exists (Batch):.
        /// </summary>
        public static string WhenFileExistsBatch {
            get {
                return ResourceManager.GetString("WhenFileExistsBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When file already exists (Single):.
        /// </summary>
        public static string WhenFileExistsSingle {
            get {
                return ResourceManager.GetString("WhenFileExistsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick only titles with width.
        /// </summary>
        public static string WidthFilterCheckBox {
            get {
                return ResourceManager.GetString("WidthFilterCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter titles by width.
        /// </summary>
        public static string WidthFilterCheckBoxAutomationName {
            get {
                return ResourceManager.GetString("WidthFilterCheckBoxAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width filter value.
        /// </summary>
        public static string WidthFilterValueAutomationName {
            get {
                return ResourceManager.GetString("WidthFilterValueAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker: {0}.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot.
        /// </summary>
        public static string WordBreakCharacter_Dot {
            get {
                return ResourceManager.GetString("WordBreakCharacter_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string WordBreakCharacter_Space {
            get {
                return ResourceManager.GetString("WordBreakCharacter_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underscore.
        /// </summary>
        public static string WordBreakCharacter_Underscore {
            get {
                return ResourceManager.GetString("WordBreakCharacter_Underscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word break character - {0}.
        /// </summary>
        public static string WordBreakCharacterAutomationNameFormat {
            get {
                return ResourceManager.GetString("WordBreakCharacterAutomationNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized word break characters:.
        /// </summary>
        public static string WordBreakCharactersLabel {
            get {
                return ResourceManager.GetString("WordBreakCharactersLabel", resourceCulture);
            }
        }
    }
}
