//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.PickerRes", typeof(PickerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio selection.
        /// </summary>
        public static string AudioSelection {
            get {
                return ResourceManager.GetString("AudioSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start encoding after scan.
        /// </summary>
        public static string AutoEncodeOnScanCheckBox {
            get {
                return ResourceManager.GetString("AutoEncodeOnScanCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically queue after scanning.
        /// </summary>
        public static string AutoQueueOnScanCheckBox {
            get {
                return ResourceManager.GetString("AutoQueueOnScanCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn in.
        /// </summary>
        public static string BurnInCheckBox {
            get {
                return ResourceManager.GetString("BurnInCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultCheckBox {
            get {
                return ResourceManager.GetString("DefaultCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Audio Search.
        /// </summary>
        public static string ForeignAudioSearchRadioButton {
            get {
                return ResourceManager.GetString("ForeignAudioSearchRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all tracks.
        /// </summary>
        public static string IncludeAllTracksCheckBox {
            get {
                return ResourceManager.GetString("IncludeAllTracksCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageRadioButton {
            get {
                return ResourceManager.GetString("LanguageRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if different language from audio.
        /// </summary>
        public static string OnlyIfDifferentFromAudioCheckBox {
            get {
                return ResourceManager.GetString("OnlyIfDifferentFromAudioCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output location.
        /// </summary>
        public static string OutputLocation {
            get {
                return ResourceManager.GetString("OutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override directory:.
        /// </summary>
        public static string OverrideDirectoryCheckBox {
            get {
                return ResourceManager.GetString("OverrideDirectoryCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker: {0}.
        /// </summary>
        public static string PickerButtonFormat {
            get {
                return ResourceManager.GetString("PickerButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically pick titles, audio, subtitles and destination.
        /// </summary>
        public static string PickerHelpText {
            get {
                return ResourceManager.GetString("PickerHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle selection.
        /// </summary>
        public static string SubtitleSelection {
            get {
                return ResourceManager.GetString("SubtitleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title selection.
        /// </summary>
        public static string TitleSelection {
            get {
                return ResourceManager.GetString("TitleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker: {0}.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
