//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PreviewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreviewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.PreviewRes", typeof(PreviewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Margin.
        /// </summary>
        public static string BottomMargin {
            get {
                return ResourceManager.GetString("BottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Video.
        /// </summary>
        public static string CloseVideoButton {
            get {
                return ResourceManager.GetString("CloseVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Preview Clip.
        /// </summary>
        public static string EncodePreviewClipButton {
            get {
                return ResourceManager.GetString("EncodePreviewClipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes and plays a small preview clip from the selected screen. Uses current encoding settings..
        /// </summary>
        public static string EncodePreviewClipToolTip {
            get {
                return ResourceManager.GetString("EncodePreviewClipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating preview....
        /// </summary>
        public static string GeneratingPreview {
            get {
                return ResourceManager.GetString("GeneratingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Margin.
        /// </summary>
        public static string LeftMargin {
            get {
                return ResourceManager.GetString("LeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: No video source.
        /// </summary>
        public static string NoVideoSourceTitle {
            get {
                return ResourceManager.GetString("NoVideoSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in System Player.
        /// </summary>
        public static string OpenInSystemPlayerButton {
            get {
                return ResourceManager.GetString("OpenInSystemPlayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Source.
        /// </summary>
        public static string PlaySourceButton {
            get {
                return ResourceManager.GetString("PlaySourceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows store version cannot play DVD or Blu-ray source as it is not allowed to launch other processes..
        /// </summary>
        public static string PlaySourceDisabledAppxToolTip {
            get {
                return ResourceManager.GetString("PlaySourceDisabledAppxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source preview for Blu-ray not supported yet..
        /// </summary>
        public static string PlaySourceDisabledBluRayToolTip {
            get {
                return ResourceManager.GetString("PlaySourceDisabledBluRayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A supported DVD player could not be found. Install VLC or MPC-HC to use this feature..
        /// </summary>
        public static string PlaySourceDisabledNoPlayerToolTip {
            get {
                return ResourceManager.GetString("PlaySourceDisabledNoPlayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find source file..
        /// </summary>
        public static string PlaySourceDisabledNotFoundToolTip {
            get {
                return ResourceManager.GetString("PlaySourceDisabledNotFoundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays the source video..
        /// </summary>
        public static string PlaySourceToolTip {
            get {
                return ResourceManager.GetString("PlaySourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview clip generation failed. See the Log window for details..
        /// </summary>
        public static string PreviewClipGenerationFailedMessage {
            get {
                return ResourceManager.GetString("PreviewClipGenerationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview clip generation failed.
        /// </summary>
        public static string PreviewClipGenerationFailedTitle {
            get {
                return ResourceManager.GetString("PreviewClipGenerationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corners.
        /// </summary>
        public static string PreviewDisplay_Corners {
            get {
                return ResourceManager.GetString("PreviewDisplay_Corners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to Window.
        /// </summary>
        public static string PreviewDisplay_FitToWindow {
            get {
                return ResourceManager.GetString("PreviewDisplay_FitToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1.
        /// </summary>
        public static string PreviewDisplay_OneToOne {
            get {
                return ResourceManager.GetString("PreviewDisplay_OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: Display {0}x{1} - Storage {2}x{3}.
        /// </summary>
        public static string PreviewWindowTitleComplex {
            get {
                return ResourceManager.GetString("PreviewWindowTitleComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: {0}x{1}.
        /// </summary>
        public static string PreviewWindowTitleSimple {
            get {
                return ResourceManager.GetString("PreviewWindowTitleSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Preview.
        /// </summary>
        public static string ReplayPreviewButton {
            get {
                return ResourceManager.GetString("ReplayPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Margin.
        /// </summary>
        public static string RightMargin {
            get {
                return ResourceManager.GetString("RightMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin.
        /// </summary>
        public static string TopMargin {
            get {
                return ResourceManager.GetString("TopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not play video with built-in player. Would you like to open with the system player?.
        /// </summary>
        public static string VideoErrorMessage {
            get {
                return ResourceManager.GetString("VideoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Error.
        /// </summary>
        public static string VideoErrorTitle {
            get {
                return ResourceManager.GetString("VideoErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View:.
        /// </summary>
        public static string ViewLabel {
            get {
                return ResourceManager.GetString("ViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VolumeSliderLabel {
            get {
                return ResourceManager.GetString("VolumeSliderLabel", resourceCulture);
            }
        }
    }
}
