//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueueTitlesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueueTitlesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.QueueTitlesRes", typeof(QueueTitlesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string LengthRangeMid {
            get {
                return ResourceManager.GetString("LengthRangeMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string LengthRangePost {
            get {
                return ResourceManager.GetString("LengthRangePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All titles from.
        /// </summary>
        public static string LengthRangePre {
            get {
                return ResourceManager.GetString("LengthRangePre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override title #: start at.
        /// </summary>
        public static string OverrideTitleCheckBox {
            get {
                return ResourceManager.GetString("OverrideTitleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When chosen, this will override the normal title for the purposes of creating the output file name. For example with titles 2, 3 and 4 and an override of 7, they will be labeled as 7, 8 and 9. Can be useful for ripping a disc of a TV series..
        /// </summary>
        public static string OverrideTitleNumberToolTip {
            get {
                return ResourceManager.GetString("OverrideTitleNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Source.
        /// </summary>
        public static string PlaySourceButton {
            get {
                return ResourceManager.GetString("PlaySourceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a supported player is installed (VLC or Media Player Classic Home Cinema), you can preview individual titles of DVDs.
        /// </summary>
        public static string PlaySourceToolTip {
            get {
                return ResourceManager.GetString("PlaySourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Multiple Titles.
        /// </summary>
        public static string QueueTitlesDialogTitle {
            get {
                return ResourceManager.GetString("QueueTitlesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick multiple titles to add to the queue..
        /// </summary>
        public static string QueueTitlesWindowHeader {
            get {
                return ResourceManager.GetString("QueueTitlesWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title {0}.
        /// </summary>
        public static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
    }
}
