//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources; 
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WatcherRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WatcherRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.WatcherRes", typeof(WatcherRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate File Watcher.
        /// </summary>
        public static string ActivateWatcherButton {
            get {
                return ResourceManager.GetString("ActivateWatcherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder to watch.
        /// </summary>
        public static string AddFolderToWatch {
            get {
                return ResourceManager.GetString("AddFolderToWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelMenuItem {
            get {
                return ResourceManager.GetString("CancelMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate File Watcher.
        /// </summary>
        public static string DeactivateWatcherButton {
            get {
                return ResourceManager.GetString("DeactivateWatcherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string OpenContainingFolderMenuItem {
            get {
                return ResourceManager.GetString("OpenContainingFolderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathColumnHeader {
            get {
                return ResourceManager.GetString("PathColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker:.
        /// </summary>
        public static string PickerLabel {
            get {
                return ResourceManager.GetString("PickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the folder to watch.
        /// </summary>
        public static string PickWatchedFolderDialogDescription {
            get {
                return ResourceManager.GetString("PickWatchedFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding preset:.
        /// </summary>
        public static string PresetLabel {
            get {
                return ResourceManager.GetString("PresetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove watched folder.
        /// </summary>
        public static string RemoveWatchedFolder {
            get {
                return ResourceManager.GetString("RemoveWatchedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryMenuItem {
            get {
                return ResourceManager.GetString("RetryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run when VidCoder is closed.
        /// </summary>
        public static string RunWhenClosedCheckBox {
            get {
                return ResourceManager.GetString("RunWhenClosedCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not install file watcher service..
        /// </summary>
        public static string ServiceInstallError {
            get {
                return ResourceManager.GetString("ServiceInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not uninstall file watcher service..
        /// </summary>
        public static string ServiceUninstallError {
            get {
                return ResourceManager.GetString("ServiceUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encode was canceled by removing from the queue..
        /// </summary>
        public static string StatusCanceledToolTip {
            get {
                return ResourceManager.GetString("StatusCanceledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusColumnHeader {
            get {
                return ResourceManager.GetString("StatusColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encode failed..
        /// </summary>
        public static string StatusFailedToolTip {
            get {
                return ResourceManager.GetString("StatusFailedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was encoded by VidCoder..
        /// </summary>
        public static string StatusOutputToolTip {
            get {
                return ResourceManager.GetString("StatusOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file is in the queue..
        /// </summary>
        public static string StatusQueuedToolTip {
            get {
                return ResourceManager.GetString("StatusQueuedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encode was skipped due to conditions set in the picker (such as a file size that is too small)..
        /// </summary>
        public static string StatusSkippedToolTip {
            get {
                return ResourceManager.GetString("StatusSkippedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encode completed successfully..
        /// </summary>
        public static string StatusSucceededToolTip {
            get {
                return ResourceManager.GetString("StatusSucceededToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string WatchedFilesHeader {
            get {
                return ResourceManager.GetString("WatchedFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch folders.
        /// </summary>
        public static string WatchedFoldersHeader {
            get {
                return ResourceManager.GetString("WatchedFoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string WatchedFolderTextBoxLabel {
            get {
                return ResourceManager.GetString("WatchedFolderTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add watched folder.
        /// </summary>
        public static string WatcherAddDialogTitle {
            get {
                return ResourceManager.GetString("WatcherAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit watched folder.
        /// </summary>
        public static string WatcherEditDialogTitle {
            get {
                return ResourceManager.GetString("WatcherEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set up the Watcher to observe folders and automatically encode videos that show up in them. The Watcher process will run when VidCoder is closed and launch it to encode files..
        /// </summary>
        public static string WatcherIntroText {
            get {
                return ResourceManager.GetString("WatcherIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher - {0}.
        /// </summary>
        public static string WatcherWindowTitle {
            get {
                return ResourceManager.GetString("WatcherWindowTitle", resourceCulture);
            }
        }
    }
