//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidCoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WatcherRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WatcherRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidCoder.Resources.WatcherRes", typeof(WatcherRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Watcher service.
        /// </summary>
        public static string InstallWatcherButton {
            get {
                return ResourceManager.GetString("InstallWatcherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not install file watcher service..
        /// </summary>
        public static string ServiceInstallError {
            get {
                return ResourceManager.GetString("ServiceInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not uninstall file watcher service..
        /// </summary>
        public static string ServiceUninstallError {
            get {
                return ResourceManager.GetString("ServiceUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Watcher service.
        /// </summary>
        public static string UninstallWatcherButton {
            get {
                return ResourceManager.GetString("UninstallWatcherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set up the Watcher to observe folders and automatically encode videos that show up in them. The Watcher service will run when VidCoder is closed and launch it to encode files..
        /// </summary>
        public static string WatcherIntroText {
            get {
                return ResourceManager.GetString("WatcherIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher.
        /// </summary>
        public static string WatcherWindowTitle {
            get {
                return ResourceManager.GetString("WatcherWindowTitle", resourceCulture);
            }
        }
    }
}
